# ❯ nix4vscode config.toml
# 2025-04-02T00:33:58.696019Z ERROR nix4vscode::code: src/code.rs:178: get sha256 failed: Fail to query sha256 of https://github.com/vadimcn/codelldb/releases/download/v1.11.4/codelldb-aarch64-macos.vsix
# Warning, this file is autogenerated by nix4vscode. Don't modify this manually.
{
  pkgs,
  lib,
}: let
  inherit (pkgs.stdenv) isDarwin isLinux isi686 isx86_64 isAarch32 isAarch64;
  vscode-utils = pkgs.vscode-utils;
  merge = lib.attrsets.recursiveUpdate;
in
  merge
  (merge
    (merge
      (merge
        {
          "4ops"."packer" = vscode-utils.extensionFromVscodeMarketplace {
            name = "packer";
            publisher = "4ops";
            version = "0.3.0";
            sha256 = "0my10qn06w5sd5cmwkghsqnn6d91f346yv9i22949s3ysz2x72v9";
          };
          "arrterian"."nix-env-selector" = vscode-utils.extensionFromVscodeMarketplace {
            name = "nix-env-selector";
            publisher = "arrterian";
            version = "1.0.11";
            sha256 = "113zx78c3219knw4qa04242404n32vnk9rb6a3ynz41dgwh1mbbl";
          };
          "bbenoist"."nix" = vscode-utils.extensionFromVscodeMarketplace {
            name = "nix";
            publisher = "bbenoist";
            version = "1.0.1";
            sha256 = "0zd0n9f5z1f0ckzfjr38xw2zzmcxg1gjrava7yahg5cvdcw6l35b";
          };
          "christian-kohler"."path-intellisense" = vscode-utils.extensionFromVscodeMarketplace {
            name = "path-intellisense";
            publisher = "christian-kohler";
            version = "2.10.0";
            sha256 = "06x9ksl4bghfpxh4n65d1d7dr11spl140p9ch4mc01nrdibgckbc";
          };
          "coolbear"."systemd-unit-file" = vscode-utils.extensionFromVscodeMarketplace {
            name = "systemd-unit-file";
            publisher = "coolbear";
            version = "1.0.6";
            sha256 = "0sc0zsdnxi4wfdlmaqwb6k2qc21dgwx6ipvri36x7agk7m8m4736";
          };
          "davidanson"."vscode-markdownlint" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-markdownlint";
            publisher = "davidanson";
            version = "0.59.0";
            sha256 = "1wha85xc441qac1cay7vmpplx56njg1w0p5h6d49r4xx2s8vpcnd";
          };
          "dbaeumer"."vscode-eslint" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-eslint";
            publisher = "dbaeumer";
            version = "3.0.10";
            sha256 = "02snfjlrgs4i9svyhipkirvwj9vqfylswzvfizk00hf8fk39wn8i";
          };
          "donjayamanne"."githistory" = vscode-utils.extensionFromVscodeMarketplace {
            name = "githistory";
            publisher = "donjayamanne";
            version = "0.6.20";
            sha256 = "0x9q7sh5l1frpvfss32ypxk03d73v9npnqxif4fjwcfwvx5mhiww";
          };
          "eamodio"."gitlens" = vscode-utils.extensionFromVscodeMarketplace {
            name = "gitlens";
            publisher = "eamodio";
            version = "17.0.0";
            sha256 = "1vpxhl31vipzkf9lcvi3mzisi503mdjkr62j5fkrsgcbz0hh49wx";
          };
          "editorconfig"."editorconfig" = vscode-utils.extensionFromVscodeMarketplace {
            name = "editorconfig";
            publisher = "editorconfig";
            version = "0.17.2";
            sha256 = "1s0a2zgxk6qxl6lzw6klkn8xhsxk0l87vcbms2k8535kvscbwbay";
          };
          "ericadamski"."carbon-now-sh" = vscode-utils.extensionFromVscodeMarketplace {
            name = "carbon-now-sh";
            publisher = "ericadamski";
            version = "1.2.0";
            sha256 = "0an0vvxz63ckn65xf85yv8z9mzd9niwfl1nxmkhh6w5g5sskhllc";
          };
          "golang"."go" = vscode-utils.extensionFromVscodeMarketplace {
            name = "go";
            publisher = "golang";
            version = "0.46.1";
            sha256 = "1fx6il5mpl6z2y68s63ssy28k8hhkj998r3rpajpckqnygm85527";
          };
          "ipedrazas"."kubernetes-snippets" = vscode-utils.extensionFromVscodeMarketplace {
            name = "kubernetes-snippets";
            publisher = "ipedrazas";
            version = "0.1.9";
            sha256 = "0gf1m9vppcsdbvdsx2k0a9xj2cfqbbm8b4iw7v8xgn4y2k6w8lq6";
          };
          "ivory-lab"."jenkinsfile-support" = vscode-utils.extensionFromVscodeMarketplace {
            name = "jenkinsfile-support";
            publisher = "ivory-lab";
            version = "1.1.0";
            sha256 = "0n30kkla6dwdzgdimqy4hkqrxhpvrgfnd2zf7c3zx328hhbznaky";
          };
          "jnoortheen"."nix-ide" = vscode-utils.extensionFromVscodeMarketplace {
            name = "nix-ide";
            publisher = "jnoortheen";
            version = "0.4.16";
            sha256 = "0mhc58lzdn153yskqi6crvzx6pgi1d72mdhmnpc4qkbf1wx47l9i";
          };
          "jq-syntax-highlighting"."jq-syntax-highlighting" = vscode-utils.extensionFromVscodeMarketplace {
            name = "jq-syntax-highlighting";
            publisher = "jq-syntax-highlighting";
            version = "0.0.2";
            sha256 = "0q91mr6a6935wnka5iga97lv78g19dlj2rz6qg3ki6w3kdlvw2h7";
          };
          "likec4"."likec4-vscode" = vscode-utils.extensionFromVscodeMarketplace {
            name = "likec4-vscode";
            publisher = "likec4";
            version = "1.27.3";
            sha256 = "02l335k4ri9wlni0s58bvf3nn2y3dx4dlsdc8s65x5z5pc6h5jz0";
          };
          "lunuan"."kubernetes-templates" = vscode-utils.extensionFromVscodeMarketplace {
            name = "kubernetes-templates";
            publisher = "lunuan";
            version = "1.3.1";
            sha256 = "0bjyx9ri7fl68ryy0icn1lc3r8gxkpwaxhh900ij8xfvabqvcx6m";
          };
          "mads-hartmann"."bash-ide-vscode" = vscode-utils.extensionFromVscodeMarketplace {
            name = "bash-ide-vscode";
            publisher = "mads-hartmann";
            version = "1.43.0";
            sha256 = "157n2m9dhb26q6yvd16rb5yi2k8k7f7v6vd03vyvvy0rhv7454i2";
          };
          "marus25"."cortex-debug" = vscode-utils.extensionFromVscodeMarketplace {
            name = "cortex-debug";
            publisher = "marus25";
            version = "1.12.1";
            sha256 = "1kbw93915a2ag3rgddyz4wnlifl6f2m9cxbxqqghfs341f1vm0la";
          };
          "mcu-debug"."debug-tracker-vscode" = vscode-utils.extensionFromVscodeMarketplace {
            name = "debug-tracker-vscode";
            publisher = "mcu-debug";
            version = "0.0.15";
            sha256 = "0wlz089z91my82kygv7kmip0nfkmgczcyl5h1hpxwzvb5ji0rvns";
          };
          "mcu-debug"."memory-view" = vscode-utils.extensionFromVscodeMarketplace {
            name = "memory-view";
            publisher = "mcu-debug";
            version = "0.0.25";
            sha256 = "0iqfblx5ayhpf1gj3szf3hn6145yqmkgqn18bhi5l9l7h8qkgjad";
          };
          "mcu-debug"."peripheral-viewer" = vscode-utils.extensionFromVscodeMarketplace {
            name = "peripheral-viewer";
            publisher = "mcu-debug";
            version = "1.4.6";
            sha256 = "1a499vnjmdxlh98h4c82dfrkafak3rj9h0wiwqrbibd0xcmq2mby";
          };
          "mcu-debug"."rtos-views" = vscode-utils.extensionFromVscodeMarketplace {
            name = "rtos-views";
            publisher = "mcu-debug";
            version = "0.0.7";
            sha256 = "1nhxhiq6a5rckfy9pqdkjbfq06c4xzlaqm4a5rq5r26a9rhh1wsn";
          };
          "mkhl"."direnv" = vscode-utils.extensionFromVscodeMarketplace {
            name = "direnv";
            publisher = "mkhl";
            version = "0.17.0";
            sha256 = "1n2qdd1rspy6ar03yw7g7zy3yjg9j1xb5xa4v2q12b0y6dymrhgn";
          };
          "ms-kubernetes-tools"."vscode-kubernetes-tools" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-kubernetes-tools";
            publisher = "ms-kubernetes-tools";
            version = "1.3.20";
            sha256 = "195l18ln3rylximnrbp86zv7sqc9p8mav4iqxbc0vyx7508rqwpk";
          };
          "ms-python"."vscode-pylance" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-pylance";
            publisher = "ms-python";
            version = "2025.3.2";
            sha256 = "0sa1xznwd0f8kq326siyipd25a2jsqj66ykap3hk9cqqbf40gzif";
          };
          "ms-vscode-remote"."remote-ssh-edit" = vscode-utils.extensionFromVscodeMarketplace {
            name = "remote-ssh-edit";
            publisher = "ms-vscode-remote";
            version = "0.87.0";
            sha256 = "1qqsnzn9z11jr72n7cl0ab6i9mv49c0ijcp699zbglv5092gmrf9";
          };
          "natqe"."reload" = vscode-utils.extensionFromVscodeMarketplace {
            name = "reload";
            publisher = "natqe";
            version = "0.0.7";
            sha256 = "1bpzv7pg80ly31l2fyi7lbdyi2w71x7w5g3p63017hlsi3ny6h4g";
          };
          "nicolasvuillamy"."vscode-groovy-lint" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-groovy-lint";
            publisher = "nicolasvuillamy";
            version = "3.3.1";
            sha256 = "1gha2rn643bz2pydr7npyrl9p79zlxqns4qmq4cdmp8py2jq92c3";
          };
          "pkief"."material-icon-theme" = vscode-utils.extensionFromVscodeMarketplace {
            name = "material-icon-theme";
            publisher = "pkief";
            version = "5.20.0";
            sha256 = "1nhmb5x773s23i2clbwqagzhz5zm0v19779kkcqpg6gwyxfcbkb7";
          };
          "plorefice"."devicetree" = vscode-utils.extensionFromVscodeMarketplace {
            name = "devicetree";
            publisher = "plorefice";
            version = "0.1.1";
            sha256 = "0yfz6rgmh9j9bq7ahcjxphj74jd8rnnlg355vffdy8xfqdirxp5r";
          };
          "probe-rs"."probe-rs-debugger" = vscode-utils.extensionFromVscodeMarketplace {
            name = "probe-rs-debugger";
            publisher = "probe-rs";
            version = "0.24.2";
            sha256 = "0d3b4xhmf6a0xcjn5g3npmnvj6c9sizhzm8acm7gdcqskh7kjsyl";
          };
          "redhat"."vscode-commons" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-commons";
            publisher = "redhat";
            version = "0.0.6";
            sha256 = "1b8nlhbrsg3kj27f1kgj8n5ak438lcfq5v5zlgf1hzisnhmcda5n";
          };
          "roscop"."activefileinstatusbar" = vscode-utils.extensionFromVscodeMarketplace {
            name = "activefileinstatusbar";
            publisher = "roscop";
            version = "1.0.3";
            sha256 = "0sbs3138hnpg4x226gyz94161i0sw7pdi4f2dcyxxwwbs86lwqp4";
          };
          "systemticks"."c4-dsl-extension" = vscode-utils.extensionFromVscodeMarketplace {
            name = "c4-dsl-extension";
            publisher = "systemticks";
            version = "3.7.1";
            sha256 = "0kn7k70l7fcw562z1ii7cpxb1zbigqh0pjsqvbnknylhj85h096j";
          };
          "tamasfe"."even-better-toml" = vscode-utils.extensionFromVscodeMarketplace {
            name = "even-better-toml";
            publisher = "tamasfe";
            version = "0.21.2";
            sha256 = "0208cms054yj2l8pz9jrv3ydydmb47wr4i0sw8qywpi8yimddf11";
          };
          "tim-koehler"."helm-intellisense" = vscode-utils.extensionFromVscodeMarketplace {
            name = "helm-intellisense";
            publisher = "tim-koehler";
            version = "0.14.3";
            sha256 = "13bs7406g4nq5wfxh90zyp4yq62wlzzwl7gzkill2a56gvrfgiad";
          };
          "whi-tw"."klipper-config-syntax" = vscode-utils.extensionFromVscodeMarketplace {
            name = "klipper-config-syntax";
            publisher = "whi-tw";
            version = "0.2.2";
            sha256 = "0v52p7s5sn3nv2h138wakc2zikdi00dqq98lrd3c0r6607dhab21";
          };
          "zixuanwang"."linkerscript" = vscode-utils.extensionFromVscodeMarketplace {
            name = "linkerscript";
            publisher = "zixuanwang";
            version = "1.0.4";
            sha256 = "0mfna6xypzfwsrmfzx898pc76ddfn4n8yr8l4d8gbhcyqyj5y3zp";
          };
        }
        (lib.attrsets.optionalAttrs (isLinux && (isi686 || isx86_64)) {
          "hashicorp"."terraform" = vscode-utils.extensionFromVscodeMarketplace {
            name = "terraform";
            publisher = "hashicorp";
            version = "2.34.3";
            sha256 = "0ladgyija724flxmagf9amj80r00c9yg2v5rjmzglj0m3wfzy56b";
            arch = "linux-x64";
          };
          "redhat"."vscode-xml" = vscode-utils.extensionFromVscodeMarketplace {
            name = "vscode-xml";
            publisher = "redhat";
            version = "0.28.0";
            sha256 = "0pipcl1r6sngf6dq3cmz3g56ww78r10r8acqjzmri6l5kxpx22ah";
            arch = "linux-x64";
          };
        }))
      (lib.attrsets.optionalAttrs (isLinux && (isAarch32 || isAarch64)) {
        "hashicorp"."terraform" = vscode-utils.extensionFromVscodeMarketplace {
          name = "terraform";
          publisher = "hashicorp";
          version = "2.34.3";
          sha256 = "0z3c1g71dp8ww8irlgdlhwnvqrksxplh8k4izvjg55mycj34pigp";
          arch = "linux-arm64";
        };
      }))
    (lib.attrsets.optionalAttrs (isDarwin && (isi686 || isx86_64)) {
      "hashicorp"."terraform" = vscode-utils.extensionFromVscodeMarketplace {
        name = "terraform";
        publisher = "hashicorp";
        version = "2.34.3";
        sha256 = "0kz2xx4i6wa52ym4nmjfb9j28lbk4hmcwkpifb23vhnni0l20d4f";
        arch = "darwin-x64";
      };
      "redhat"."vscode-xml" = vscode-utils.extensionFromVscodeMarketplace {
        name = "vscode-xml";
        publisher = "redhat";
        version = "0.28.0";
        sha256 = "1mdjb3app4b34fzxi34rqgz4jjn0vhwjyhlgh7rlcnavqsk4amzg";
        arch = "darwin-x64";
      };
    }))
  (lib.attrsets.optionalAttrs (isDarwin && (isAarch32 || isAarch64)) {
    "hashicorp"."terraform" = vscode-utils.extensionFromVscodeMarketplace {
      name = "terraform";
      publisher = "hashicorp";
      version = "2.34.3";
      sha256 = "0bcngqbk7mp4131dqb0x1cw32m7ssr8c0sx819d8vvr98wgp2kwh";
      arch = "darwin-arm64";
    };
    "redhat"."vscode-xml" = vscode-utils.extensionFromVscodeMarketplace {
      name = "vscode-xml";
      publisher = "redhat";
      version = "0.28.0";
      sha256 = "1wzb8rxf420ggrnl4z83zps2n6k02mqk32yxvaa8fqcvscf0c7jw";
      arch = "darwin-arm64";
    };
  })
