vscode_version = "1.96.2"

[[extensions]]
publisher_name = "4ops"
extension_name = "packer"

[[extensions]]
publisher_name = "arrterian"
extension_name = "nix-env-selector"

[[extensions]]
publisher_name = "bbenoist"
extension_name = "nix"

[[extensions]]
publisher_name = "christian-kohler"
extension_name = "path-intellisense"

[[extensions]]
publisher_name = "coolbear"
extension_name = "systemd-unit-file"

[[extensions]]
publisher_name = "davidanson"
extension_name = "vscode-markdownlint"

[[extensions]]
publisher_name = "dbaeumer"
extension_name = "vscode-eslint"

[[extensions]]
publisher_name = "donjayamanne"
extension_name = "githistory"

[[extensions]]
publisher_name = "eamodio"
extension_name = "gitlens"

[[extensions]]
publisher_name = "editorconfig"
extension_name = "editorconfig"

[[extensions]]
publisher_name = "ericadamski"
extension_name = "carbon-now-sh"

[[extensions]]
publisher_name = "golang"
extension_name = "go"

[[extensions]]
publisher_name = "hashicorp"
extension_name = "terraform"

[[extensions]]
publisher_name = "ipedrazas"
extension_name = "kubernetes-snippets"

[[extensions]]
publisher_name = "ivory-lab"
extension_name = "jenkinsfile-support"

[[extensions]]
publisher_name = "jnoortheen"
extension_name = "nix-ide"

[[extensions]]
publisher_name = "jq-syntax-highlighting"
extension_name = "jq-syntax-highlighting"

[[extensions]]
publisher_name = "likec4"
extension_name = "likec4-vscode"

[[extensions]]
publisher_name = "lunuan"
extension_name = "kubernetes-templates"

[[extensions]]
publisher_name = "mads-hartmann"
extension_name = "bash-ide-vscode"

[[extensions]]
publisher_name = "marus25"
extension_name = "cortex-debug"

[[extensions]]
publisher_name = "mcu-debug"
extension_name = "debug-tracker-vscode"

[[extensions]]
publisher_name = "mcu-debug"
extension_name = "memory-view"

[[extensions]]
publisher_name = "mcu-debug"
extension_name = "peripheral-viewer"

[[extensions]]
publisher_name = "mcu-debug"
extension_name = "rtos-views"

[[extensions]]
publisher_name = "mkhl"
extension_name = "direnv"

[[extensions]]
publisher_name = "ms-kubernetes-tools"
extension_name = "vscode-kubernetes-tools"

[[extensions]]
publisher_name = "ms-python"
extension_name = "vscode-pylance"

[[extensions]]
publisher_name = "ms-vscode-remote"
extension_name = "remote-ssh-edit"

[[extensions]]
publisher_name = "natqe"
extension_name = "reload"

[[extensions]]
publisher_name = "nicolasvuillamy"
extension_name = "vscode-groovy-lint"

[[extensions]]
publisher_name = "pkief"
extension_name = "material-icon-theme"

[[extensions]]
publisher_name = "plorefice"
extension_name = "devicetree"

[[extensions]]
publisher_name = "probe-rs"
extension_name = "probe-rs-debugger"

[[extensions]]
publisher_name = "redhat"
extension_name = "vscode-commons"

[[extensions]]
publisher_name = "redhat"
extension_name = "vscode-xml"

[[extensions]]
publisher_name = "redhat"
extension_name = "vscode-yaml"

[[extensions]]
publisher_name = "roscop"
extension_name = "activefileinstatusbar"

[[extensions]]
publisher_name = "systemticks"
extension_name = "c4-dsl-extension"

[[extensions]]
publisher_name = "tamasfe"
extension_name = "even-better-toml"

[[extensions]]
publisher_name = "tim-koehler"
extension_name = "helm-intellisense"

[[extensions]]
publisher_name = "vadimcn"
extension_name = "vscode-lldb"

[[extensions]]
publisher_name = "whi-tw"
extension_name = "klipper-config-syntax"

[[extensions]]
publisher_name = "zixuanwang"
extension_name = "linkerscript"