branches:
  - name: master
    protection:
      enforce_admins: false
      required_pull_request_reviews: null
      required_status_checks:
        contexts:
          - build_system
          - build_shell
        strict: true
      restrictions: null
repository:
  allow_merge_commit: true
  allow_rebase_merge: false
  allow_squash_merge: true
  default_branch: master
  delete_branch_on_merge: true
  description: My Nix-managed stuff configuration
  has_downloads: false
  has_issues: false
  has_projects: false
  has_wiki: false
  name: infra
  private: false
  topics: nix, nixos, nix-darwin, flake-parts, flake, flakes, nix-flake, nix-flakes, haumea, deploy-rs, nixago
