
env:
  CACHIX_AUTH_TOKEN: ENCRYPTED[b9defe725a79a0699b0f8916ee1e7654a4ef73e0a70ede58b9cc51ec5d8638da982e48e6dd6bfc9c6b3c215fe819c2a5]
  NIX: nix --extra-experimental-features nix-command --extra-experimental-features flakes
  # CIRRUS_SHELL: "/bin/bash"

common_task_template: &COMMON_TASK_TEMPLATE
  timeout_in: 60m
  only_if: $CIRRUS_BRANCH == 'master' || $CIRRUS_PR != ''

common_scripts_template: &COMMON_SCRIPTS_TEMPLATE
  # TODO add cache?
  # nix_cache:

  prepare_nix_env_script:
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  # TODO pin or something
  - nix-channel --add https://nixos.org/channels/nixpkgs-unstable
  - nix-channel --update
  - git config --global --add safe.directory "$(pwd)"

  - echo $CACHIX_AUTH_TOKEN | cachix authtoken --stdin
  - cachix use nix-community
  - cachix use mic92
  - cachix use nrdxp
  - cachix use truelecter
  - ./.ci/install-nix.sh > /tmp/store-path-pre-build

common_finishing_script_template: &COMMON_FINISHING_SCRIPTS_TEMPLATE
  upload_paths_to_cachix_script: .ci/push-paths.sh cachix "--compression-method xz --compression-level 9 --jobs 8" truelecter ""  ""

macos_task:
  << : *COMMON_TASK_TEMPLATE

  name: Build Nix-Darwin system

  env:
    NIXOS_HOST: nonexisting
    USER: "admin"
    HOME: "/Users/admin"
    PATH: "$HOME/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/per-user/$USER/profile/bin:$PATH"
    NIX_SSL_CERT_FILE: /nix/var/nix/profiles/default/etc/ssl/certs/ca-bundle.crt
    CIRRUS_SHELL: "/bin/zsh"

  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-xcode:14.2

  install_nix_script: ./.ci/install-nix.sh

  << : *COMMON_SCRIPTS_TEMPLATE

  build_system_script:
  - nix build ".#darwinConfigurations.darwin-$NIXOS_HOST.config.system.build.toplevel"

  build_devshell_script:
  - nix develop --command "menu"

  << : *COMMON_FINISHING_SCRIPTS_TEMPLATE

  matrix:
  - name: Build squadbook
    env:
      NIXOS_HOST: squadbook
