keys:
  - &truelecter A35AABA719FAC1A001E375F8EEF7F5B1C5AB1F74
  - &server-nas 70732b3ee3a1c10a8b6b849a959a413b28c00df9
  - &squadbook 4b2db161a7459a355a6f7b3006f1ae8861b01531
  - &octoprint 50b24bfd5de5ee6397d7138de6f9c0f528fd86f3
  - &hyperos 51add5cfe4c21755f8685d7372065280e76b908e
  - &depsos 356a82c0e351bd86b093e96706f5748b0e47bff0
  - &oracle 70e8bfb15ea96c3752baafcfc43cfc3d2c42d68e
  - &tl-wsl ceb6cea45e8d7d34c25d166868696097610a4f62
  - &voron ad74ae276ddcd3b8c05242fc537e0afff9393519
  - &rockiosk ef5e9b1601de92796784e3cd146a31ffb1cc2f5d
  - &pikiosk 2994ee04eda55d05dae7019ed74ef11ed4a030bc
  - &trizero 626de251782cdf224d7f89a4277110395ef8b6e3
  - &print-farm 3901b2e5705df031bb41338c5ba8634804f9940d

creation_rules:
  - path_regex: cells/secrets/sops/envs.yaml
    key_groups:
      - pgp:
          - *truelecter

  - path_regex: cells/secrets/sops/minecraft-server.yaml
    key_groups:
      - pgp:
          - *truelecter
          - *oracle

  - path_regex: cells/secrets/sops/nixos-common.yaml
    key_groups:
      - pgp:
          - *truelecter
          - *server-nas
          - *octoprint
          - *hyperos
          - *depsos
          - *oracle
          - *tl-wsl
          - *voron
          - *rockiosk
          - *pikiosk
          - *trizero
          - *print-farm

  - path_regex: cells/secrets/sops/k3s.yaml
    key_groups:
      - pgp:
          - *truelecter
          - *depsos

  - path_regex: cells/secrets/sops/external-ips.yaml
    key_groups:
      - pgp:
          - *truelecter
          - *depsos

  - path_regex: cells/secrets/sops/wifi.yaml
    key_groups:
      - pgp:
          - *truelecter
          - *squadbook
          - *octoprint
          - *voron
          - *rockiosk
          - *pikiosk
          - *trizero
          - *print-farm

  - path_regex: cells/secrets/sops/ssh.*$
    key_groups:
      - pgp:
          - *truelecter
          - *squadbook
          - *tl-wsl

  - path_regex: cells/secrets/sops/weather-kiosk.yaml
    key_groups:
      - pgp:
          - *truelecter
          - *rockiosk
          - *pikiosk
