keys:
  - &truelecter A35AABA719FAC1A001E375F8EEF7F5B1C5AB1F74
  - &server-nas 70732b3ee3a1c10a8b6b849a959a413b28c00df9
  - &squadbook 4b2db161a7459a355a6f7b3006f1ae8861b01531
  - &octoprint 50b24bfd5de5ee6397d7138de6f9c0f528fd86f3
  - &hyperos 51add5cfe4c21755f8685d7372065280e76b908e
  - &depsos 356a82c0e351bd86b093e96706f5748b0e47bff0
  - &oracle 70e8bfb15ea96c3752baafcfc43cfc3d2c42d68e

creation_rules:
  - path_regex: cells/secrets/sops/envs.yaml
    key_groups:
      - pgp:
          - *truelecter
  - path_regex: secrets/sops/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *truelecter
          - *server-nas
          - *squadbook
          - *octoprint
          - *hyperos
          - *depsos
          - *oracle
  - path_regex: secrets/sops/ssh.*$
    key_groups:
      - pgp:
          - *truelecter
