[mp-server-pause-forge-1_16_5]
src.manual = "1.1.0"
fetch.url = "https://www.curseforge.com/api/v1/mods/556491/files/3803691/download"
passthru = { mod = "forge", mc-version = "1.16.5", name = "mp-server-pause" }

[mod-sponge-changeskin]
src.manual = "3.2"
fetch.url = "https://ci.codemc.io/job/Games647/job/ChangeSkin/474/artifact/sponge/target/ChangeSkinSponge.jar"
passthru = { mod = "sponge", mc-version = "7", name = "change-skin" }

[mod-changeskincore]
src.manual = "3.2"
fetch.url = "https://ci.codemc.io/job/Games647/job/ChangeSkin/474/artifact/core/target/ChangeSkinCore.jar"
passthru = { mod = "sponge", mc-version = "7",name = "change-skin-core" }

[mod-forge-spongeforge]
src.manual = "1.12.2-2838-7.4.7"
fetch.url = "https://repo.spongepowered.org/repository/maven-releases/org/spongepowered/spongeforge/$ver/spongeforge-$ver.jar"
passthru = { mod = "forge", mc-version = "1.12.2", name = "spongeforge" }

[mod-forge-19-2-dynmap]
src.manual = "3.7-beta-4"
fetch.url = "https://mediafilez.forgecdn.net/files/4979/21/Dynmap-3.7-beta-4-forge-1.19.2.jar"
passthru = { mod = "forge", mc-version = "1.19.2", name = "dynmap" }

[mod-forge-19-dynmap-blockscan]
src.manual = "3.7-SNAPSHOT"
fetch.url = "https://dynmap.us/builds/DynmapBlockScan/DynmapBlockScan-3.7-SNAPSHOT-forge-1.19.jar"
passthru = { mod = "forge", mc-version = "1.19", name = "dynmap-block-scan" }

[mod-forge-19-bluemap]
src.manual = "3.13"
fetch.url = "https://github.com/BlueMap-Minecraft/BlueMap/releases/download/v3.13/BlueMap-3.13-forge-1.19.1.jar"
passthru = { mod = "forge", mc-version = "1.19.1", name = "bluemap" }

[mod-forge-18-bluemap]
src.manual = "5.2"
fetch.url = "https://github.com/BlueMap-Minecraft/BlueMap/releases/download/v5.2/BlueMap-5.2-forge-1.18.1.jar"
passthru = { mod = "forge", mc-version = "1.18.1", name = "bluemap" }

[mod-forge-192-corail-tombstone]
src.manual = "8.2.16"
fetch.url = "https://mediafilez.forgecdn.net/files/5202/57/tombstone-1.19.2-8.2.16.jar"
passthru = { mod = "forge", mc-version = "1.19.2", name = "corail-tombstone" }

[mod-forge-192-carryon]
src.manual = "2.1.2.23"
fetch.url = "https://mediafilez.forgecdn.net/files/5141/759/carryon-forge-1.19.2-2.1.2.23.jar"
passthru = { mod = "forge", mc-version = "1.19.2", name = "carryon" }

[mod-forge-192-passablefolliage]
src.manual = "5.2.1"
fetch.url = "https://mediafilez.forgecdn.net/files/4542/72/PassableFoliage-1.19.1-forge-5.2.1.jar"
passthru = { mod = "forge", mc-version = "1.19.2", name = "passable-foliage" }

[mod-forge-192-kiwi]
src.manual = "8.3.6"
fetch.url = "https://mediafilez.forgecdn.net/files/5063/293/Kiwi-1.19.2-forge-8.3.6.jar"
passthru = { mod = "forge", mc-version = "1.19.2", name = "kiwi" }

[mod-forge-192-ftb-chunks]
src.manual = "1902.4.4"
fetch.url = "https://mediafilez.forgecdn.net/files/5001/266/ftb-chunks-forge-1902.4.4-build.326.jar"
passthru = { mod = "forge", mc-version = "1.19.2", name = "ftb-chunks" }

[mod-forge-192-ftb-xmod-compat]
src.manual = "1.2.3"
fetch.url = "https://mediafilez.forgecdn.net/files/4857/341/ftb-xmod-compat-forge-1.2.3.jar"
passthru = { mod = "forge", mc-version = "1.19.2", name = "ftb-xmod-compat" }

[mod-forge-182-functional-storage]
src.manual = "1.1.4"
fetch.url = "https://mediafilez.forgecdn.net/files/5271/589/functionalstorage-1.18.2-1.1.4.jar"
passthru = { mod = "forge", mc-version = "1.18.2", name = "functional-storage" }

[mod-forge-182-easier-sleeping]
src.manual  = "2.1.0"
fetch.url = "https://mediafilez.forgecdn.net/files/3683/922/EasierSleeping-1.18.2-2.1.0.jar"
passthru = { mod = "forge", mc-version = "1.18.2", name = "easier-sleeping" }