version: 2.1

workflows:
  version: 2
  workflow:
    jobs:
      - build

orbs:
  nix: eld/nix@1.1.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.07.1
    resource_class: arm.medium
    steps:
      - nix/install:
          channels: nixpkgs=https://nixos.org/channels/nixpkgs-unstable
          extra-conf: |
            experimental-features = flakes nix-command
      - nix/install-cachix
      - run:
          name: Setup cachix repos
          command: |
            cachix use nix-community
            cachix use mic92
            cachix use nrdxp
      - checkout
      - run:
          name: Build system
          command: |
            cachix watch-exec --compression-method xz --compression-level 9 --jobs 8 truelecter -- nix build ".#nixosConfigurations.nixos-oracle.config.system.build.toplevel"
