# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  s5cmd = {
    pname = "s5cmd";
    version = "1631a0d6b20f1456e39b9ae5f1d7e8b5b082aa64";
    src = fetchFromGitHub {
      owner = "peak";
      repo = "s5cmd";
      rev = "1631a0d6b20f1456e39b9ae5f1d7e8b5b082aa64";
      fetchSubmodules = false;
      sha256 = "sha256-KUNf6iC6r52Bn6XAm8AsURSP2ncDNRz2+/e8XkTXvDo=";
    };
    date = "2023-09-20";
  };
  tfenv = {
    pname = "tfenv";
    version = "1ccfddb22005b34eacaf06a9c33f58f14e816ec9";
    src = fetchFromGitHub {
      owner = "tfutils";
      repo = "tfenv";
      rev = "1ccfddb22005b34eacaf06a9c33f58f14e816ec9";
      fetchSubmodules = false;
      sha256 = "sha256-UNvLJQB47IRcNZpoUGXTW2g63ApijnIB3oUb7Zu4lUY=";
    };
    date = "2022-10-01";
  };
  transmissionic = {
    pname = "transmissionic";
    version = "v1.8.0";
    src = fetchurl {
      url = "https://github.com/6c65726f79/Transmissionic/releases/download/v1.8.0/Transmissionic-webui-v1.8.0.zip";
      sha256 = "sha256-IhbJCv9SWjLspJYv6dBKrooGk+vA7sq1N3WzMne6PEw=";
    };
  };
}
