# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cypress-aarch64 = {
    pname = "cypress-aarch64";
    version = "10.10.0";
    src = fetchurl {
      url = "https://cdn.cypress.io/desktop/10.10.0/linux-arm64/cypress.zip";
      sha256 = "sha256-izMbLdQj0B3/Bha9rjYlaLqdQvptJMrLBWGkz8abP8c=";
    };
  };
  klipper = {
    pname = "klipper";
    version = "7511151ac95acb9f55efffa2ad5780bf2683d977";
    src = fetchFromGitHub ({
      owner = "Klipper3d";
      repo = "klipper";
      rev = "7511151ac95acb9f55efffa2ad5780bf2683d977";
      fetchSubmodules = false;
      sha256 = "sha256-yceqf3kO2wJks8eKTffFYjuxkPKFWkOJpAaL3pRiDpQ=";
    });
    date = "2023-05-14";
  };
  klipper-led_effect = {
    pname = "klipper-led_effect";
    version = "35cf587fe958fe15a07c11b60564856582890460";
    src = fetchFromGitHub ({
      owner = "julianschill";
      repo = "klipper-led_effect";
      rev = "35cf587fe958fe15a07c11b60564856582890460";
      fetchSubmodules = false;
      sha256 = "sha256-AZase17sO85Bp14DocUn+m6jT8P5ABXBJFdH7t4ANog=";
    });
    date = "2023-02-04";
  };
  klipper-screen = {
    pname = "klipper-screen";
    version = "a77148b6036c196bff86dcab4705341b3e8aa0b8";
    src = fetchFromGitHub ({
      owner = "jordanruthe";
      repo = "KlipperScreen";
      rev = "a77148b6036c196bff86dcab4705341b3e8aa0b8";
      fetchSubmodules = false;
      sha256 = "sha256-0VZ8f+b3hUjU5AUK2NJmfyzScb3M1c++PuraZk8wRAs=";
    });
    date = "2023-05-14";
  };
  libcamera = {
    pname = "libcamera";
    version = "06bbff9c23d5a85acd65595216c6b75094891f72";
    src = fetchFromGitHub ({
      owner = "raspberrypi";
      repo = "libcamera";
      rev = "06bbff9c23d5a85acd65595216c6b75094891f72";
      fetchSubmodules = false;
      sha256 = "sha256-H3Zv2CFH4BU5+vBC28wIGSkTUuWaQhqjUdv8R/bfdRc=";
    });
    date = "2023-03-13";
  };
  libcamera-apps = {
    pname = "libcamera-apps";
    version = "6e0c66a1b2c3f6bfa3d03d06b4a75d7c4006b28b";
    src = fetchFromGitHub ({
      owner = "raspberrypi";
      repo = "libcamera-apps";
      rev = "6e0c66a1b2c3f6bfa3d03d06b4a75d7c4006b28b";
      fetchSubmodules = false;
      sha256 = "sha256-jfqS6518G8RKzQz8FS9xVBQakGX39C4OO+0l/MHmNU4=";
    });
    date = "2023-05-11";
  };
  mainsail-raw = {
    pname = "mainsail-raw";
    version = "140d796f518cbb2eb72b2394a02c9dfa504fe1fd";
    src = fetchFromGitHub ({
      owner = "mainsail-crew";
      repo = "mainsail";
      rev = "140d796f518cbb2eb72b2394a02c9dfa504fe1fd";
      fetchSubmodules = false;
      sha256 = "sha256-+EqLxCUOBdjBwN9AmNuvXVGAQPQCUchrqvhEodcORHI=";
    });
    date = "2023-05-12";
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
    date = "2021-04-20";
  };
  moonraker = {
    pname = "moonraker";
    version = "b21f177e951f70a0967b4967b1d43d2bfde02e1b";
    src = fetchFromGitHub ({
      owner = "Arksine";
      repo = "moonraker";
      rev = "b21f177e951f70a0967b4967b1d43d2bfde02e1b";
      fetchSubmodules = false;
      sha256 = "sha256-QXsN+wQYxPHllvJTyBbAfGsVAsR8nYzdrZHkh01O0+Q=";
    });
    date = "2023-05-07";
  };
  moonraker-telegram-bot = {
    pname = "moonraker-telegram-bot";
    version = "b1285e0155040b92fba34b80f07c63dda91dfa5b";
    src = fetchFromGitHub ({
      owner = "nlef";
      repo = "moonraker-telegram-bot";
      rev = "b1285e0155040b92fba34b80f07c63dda91dfa5b";
      fetchSubmodules = false;
      sha256 = "sha256-+fy0NUP8XTCs4KGIq5dsgF558d9NXOmFFGT7CkT5bN0=";
    });
    date = "2023-05-13";
  };
  otf2bdf = {
    pname = "otf2bdf";
    version = "4fb7b6546c62e212475ecd61dee7d7255a60fc99";
    src = fetchFromGitHub ({
      owner = "jirutka";
      repo = "otf2bdf";
      rev = "4fb7b6546c62e212475ecd61dee7d7255a60fc99";
      fetchSubmodules = false;
      sha256 = "sha256-8z1uqUhUPK+fMW3PLkvF3eSlSJpo0x+6NQ6vYsEMqoM=";
    });
    date = "2021-09-18";
  };
  pam-reattach = {
    pname = "pam-reattach";
    version = "0fbdc4cebce66179cb2daee3d88944acd6cef505";
    src = fetchFromGitHub ({
      owner = "fabianishere";
      repo = "pam_reattach";
      rev = "0fbdc4cebce66179cb2daee3d88944acd6cef505";
      fetchSubmodules = false;
      sha256 = "sha256-9N944FcYM72hpTkT7jZoOoG7KfWvIhROHKXDh+dNTOQ=";
    });
    date = "2022-07-15";
  };
  python-networkmanager = {
    pname = "python-networkmanager";
    version = "2.2";
    src = fetchurl {
      url = "https://pypi.io/packages/source/p/python-networkmanager/python-networkmanager-2.2.tar.gz";
      sha256 = "sha256-3m65IdlKunVJ9CjtKzqkgqXVQ+y2lly6oPu1VasxudU=";
    };
  };
  rel = {
    pname = "rel";
    version = "db67af684650c8915b7ee279969a813d438ecaf7";
    src = fetchFromGitHub ({
      owner = "bubbleboy14";
      repo = "registeredeventlistener";
      rev = "db67af684650c8915b7ee279969a813d438ecaf7";
      fetchSubmodules = false;
      sha256 = "sha256-gwirX/X/0Q2fo7607ILjB3kMBIvoksUmWkQvjG6KsYg=";
    });
    date = "2023-04-14";
  };
  rtsp-simple-server = {
    pname = "rtsp-simple-server";
    version = "79562b15ab342bb34d29ffc3cae6a076ed51490a";
    src = fetchFromGitHub ({
      owner = "aler9";
      repo = "rtsp-simple-server";
      rev = "79562b15ab342bb34d29ffc3cae6a076ed51490a";
      fetchSubmodules = false;
      sha256 = "sha256-ouHkxWLcGGKKKdNTs2qSzuaUGAW73vxvq9EbgiXpzsg=";
    });
  };
  s5cmd = {
    pname = "s5cmd";
    version = "3e080613218175bb7b1f62cf45cee16eee901792";
    src = fetchFromGitHub ({
      owner = "peak";
      repo = "s5cmd";
      rev = "3e080613218175bb7b1f62cf45cee16eee901792";
      fetchSubmodules = false;
      sha256 = "sha256-jhjptEDak591vziIj6CIc4I85MM73EVi+OyBAfFOtkg=";
    });
    date = "2023-02-02";
  };
  tfenv = {
    pname = "tfenv";
    version = "1ccfddb22005b34eacaf06a9c33f58f14e816ec9";
    src = fetchFromGitHub ({
      owner = "tfutils";
      repo = "tfenv";
      rev = "1ccfddb22005b34eacaf06a9c33f58f14e816ec9";
      fetchSubmodules = false;
      sha256 = "sha256-UNvLJQB47IRcNZpoUGXTW2g63ApijnIB3oUb7Zu4lUY=";
    });
    date = "2022-10-01";
  };
  transmissionic = {
    pname = "transmissionic";
    version = "v1.8.0";
    src = fetchurl {
      url = "https://github.com/6c65726f79/Transmissionic/releases/download/v1.8.0/Transmissionic-webui-v1.8.0.zip";
      sha256 = "sha256-IhbJCv9SWjLspJYv6dBKrooGk+vA7sq1N3WzMne6PEw=";
    };
  };
  wsaccel = {
    pname = "wsaccel";
    version = "0.6.4";
    src = fetchurl {
      url = "https://pypi.io/packages/source/w/wsaccel/wsaccel-0.6.4.tar.gz";
      sha256 = "sha256-y/ZqiLyvbGrRbVDqKSFYkVJrbpk8S8ftRLBE7m/jrT0=";
    };
  };
  zig = {
    pname = "zig";
    version = "d42a719e8f7ba31a9e18d6be9d58691b0b38c69a";
    src = fetchFromGitHub ({
      owner = "ziglang";
      repo = "zig";
      rev = "d42a719e8f7ba31a9e18d6be9d58691b0b38c69a";
      fetchSubmodules = false;
      sha256 = "sha256-FwXvZBpe7rSKte17TkeeQs4is2/nsYyi9oxcv/09NSY=";
    });
  };
}
