# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  forge-server-14-23-5-2860 = {
    pname = "forge-server-14-23-5-2860";
    version = "14.23.5.2860";
    src = fetchurl {
      url = "https://maven.minecraftforge.net/net/minecraftforge/forge/1.12.2-14.23.5.2860/forge-1.12.2-14.23.5.2860-installer.jar";
      sha256 = "sha256-6nwzupXjmTqY0OnjgWjAdZ7DI6GGdacdk44fP3Dm6Oc=";
    };
  };
  forge-server-40-2-9 = {
    pname = "forge-server-40-2-9";
    version = "40.2.9";
    src = fetchurl {
      url = "https://maven.minecraftforge.net/net/minecraftforge/forge/1.18.2-40.2.9/forge-1.18.2-40.2.9-installer.jar";
      sha256 = "sha256-UUPQjoHir9F18SF+JkUJKoMMfv4s7gJcLsBaCZTEXl4=";
    };
  };
  knock = {
    pname = "knock";
    version = "a690305c6d960374fd9b1024db85a8cdfa0bf1a4";
    src = fetchFromGitHub {
      owner = "Metalcape";
      repo = "knock";
      rev = "a690305c6d960374fd9b1024db85a8cdfa0bf1a4";
      fetchSubmodules = false;
      sha256 = "sha256-RHSNvaQdIUjzN7MCDyLOosHo22CSkFlzCERCg0TFxhI=";
    };
    date = "2023-03-10";
  };
  mcs-create-arcane-engineering = {
    pname = "mcs-create-arcane-engineering";
    version = "0.1.9.3";
    src = fetchurl {
      url = "https://mediafilez.forgecdn.net/files/4852/56/CAEServer1.9.zip";
      sha256 = "sha256-0Fd2g/5yK7z46zKfV0gH6uKCBKcKoceYhIjUUdwgcIo=";
    };
  };
  mcs-dawncraft = {
    pname = "mcs-dawncraft";
    version = "1.28_f2";
    src = fetchurl {
      url = "https://mediafilez.forgecdn.net/files/4709/791/DawnCraft+1.28_f2+Serverpack.zip";
      sha256 = "sha256-kq1MjOpQXLRsCGjIdSh9L5ZgSQpUbnRZlBLNcti9khs=";
    };
  };
  mcs-enigmatica-6-expert = {
    pname = "mcs-enigmatica-6-expert";
    version = "1.8.0";
    src = fetchurl {
      url = "https://mediafilez.forgecdn.net/files/4437/745/Enigmatica6ExpertServer-1.8.0.zip";
      sha256 = "sha256-rmMzXGBqKREWKqUqJ8nNfZOyngamfukA15AmUTjKKIY=";
    };
  };
  mcs-enigmatica-9-expert = {
    pname = "mcs-enigmatica-9-expert";
    version = "1.22.1";
    src = fetchurl {
      url = "https://mediafilez.forgecdn.net/files/5356/769/Enigmatica9ExpertServer-1.22.1.zip";
      sha256 = "sha256-LgI2Rr+hjQcDXOZygxafXAcd7mvneZlkMHGC2tuI3dU=";
    };
  };
  mcs-life-in-the-village-3 = {
    pname = "mcs-life-in-the-village-3";
    version = "2.8";
    src = fetchurl {
      url = "https://mediafilez.forgecdn.net/files/5290/323/LITV3-1.19.2-Serverpack-2.8.zip";
      sha256 = "sha256-RvfEyNzvv+qKxM8FhgujP3jHfrN5Udb+cIJJLlshjRQ=";
    };
  };
  mcs-sevtech-ages = {
    pname = "mcs-sevtech-ages";
    version = "3.2.3";
    src = fetchurl {
      url = "https://mediafilez.forgecdn.net/files/3570/46/SevTech_Ages_Server_3.2.3.zip";
      sha256 = "sha256-StrvXb/5/6sf1vdEB3JUXAsuaRsWPXRcnvZkwMATHpQ=";
    };
  };
  server-starter = {
    pname = "server-starter";
    version = "2.4.1";
    src = fetchurl {
      url = "https://github.com/EnigmaticaModpacks/ServerStarter/releases/download/v2.4.1/serverstarter-2.4.1.jar";
      sha256 = "sha256-y4/5dG/w7DSb3xZ2jxeplB0I06qCTYNM0+bxxnGUHtA=";
    };
  };
}
