[knock]
src.git = "https://github.com/Metalcape/knock"
src.branch = "cooldown"
fetch.github = "Metalcape/knock"

[server-starter]
src.github = "EnigmaticaModpacks/ServerStarter"
src.prefix = "v"
fetch.url = "https://github.com/EnigmaticaModpacks/ServerStarter/releases/download/v$ver/serverstarter-$ver.jar"

[mcs-enigmatica-6-expert]
src.manual = "1.8.0"
fetch.url = "https://mediafilez.forgecdn.net/files/4437/745/Enigmatica6ExpertServer-1.8.0.zip"

[mcs-enigmatica-9-expert]
src.manual = "1.22.1"
fetch.url = "https://mediafilez.forgecdn.net/files/5356/769/Enigmatica9ExpertServer-1.22.1.zip"

[mcs-dawncraft]
src.manual = "1.28_f2"
fetch.url = "https://mediafilez.forgecdn.net/files/4709/791/DawnCraft+1.28_f2+Serverpack.zip"

[mcs-create-arcane-engineering]
src.manual = "0.1.9.3"
fetch.url = "https://mediafilez.forgecdn.net/files/4852/56/CAEServer1.9.zip"

[forge-server-40-2-9]
src.manual = "40.2.9"
fetch.url = "https://maven.minecraftforge.net/net/minecraftforge/forge/1.18.2-$ver/forge-1.18.2-$ver-installer.jar"

[forge-server-14-23-5-2860]
src.manual = "14.23.5.2860"
fetch.url = "https://maven.minecraftforge.net/net/minecraftforge/forge/1.12.2-$ver/forge-1.12.2-$ver-installer.jar"

[mcs-sevtech-ages]
src.manual = "3.2.3"
fetch.url = "https://mediafilez.forgecdn.net/files/3570/46/SevTech_Ages_Server_3.2.3.zip"

[mcs-life-in-the-village-3]
src.manual = "2.8"
fetch.url = "https://mediafilez.forgecdn.net/files/5290/323/LITV3-1.19.2-Serverpack-2.8.zip"