# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  graalvm-ee-17-aarch64-linux = {
    pname = "graalvm-ee-17-aarch64-linux";
    version = "22.3.1";
    src = fetchTarball {
      url = "https://oca.opensource.oracle.com/gds/GRAALVM_EE_JAVA17_22_3_1/graalvm-ee-java17-linux-aarch64-22.3.1.tar.gz";
      sha256 = "sha256-UomOanK5WJmx58OvMCDr5JBPPVrQ3jMyJfQYWD2xeAY=";
    };
  };
  graalvm-ee-17-x86_64-darwin = {
    pname = "graalvm-ee-17-x86_64-darwin";
    version = "22.3.1";
    src = fetchTarball {
      url = "https://oca.opensource.oracle.com/gds/GRAALVM_EE_JAVA17_22_3_1/graalvm-ee-java17-darwin-amd64-22.3.1.tar.gz";
      sha256 = "sha256-2s2B6FYO8lvOj9uVl4gTiDcQDix9/KkFGWDeyqcu30c=";
    };
  };
  graalvm-ee-17-x86_64-linux = {
    pname = "graalvm-ee-17-x86_64-linux";
    version = "22.3.1";
    src = fetchTarball {
      url = "https://oca.opensource.oracle.com/gds/GRAALVM_EE_JAVA17_22_3_1/graalvm-ee-java17-linux-amd64-22.3.1.tar.gz";
      sha256 = "sha256-M0mQAchpPt09lQvZePyaIQ86Hw1QZvghY7FTEeanRTc=";
    };
  };
  knock = {
    pname = "knock";
    version = "a690305c6d960374fd9b1024db85a8cdfa0bf1a4";
    src = fetchFromGitHub {
      owner = "Metalcape";
      repo = "knock";
      rev = "a690305c6d960374fd9b1024db85a8cdfa0bf1a4";
      fetchSubmodules = false;
      sha256 = "sha256-RHSNvaQdIUjzN7MCDyLOosHo22CSkFlzCERCg0TFxhI=";
    };
    date = "2023-03-10";
  };
  mcs-enigmatica-6-expert = {
    pname = "mcs-enigmatica-6-expert";
    version = "1.8.0";
    src = fetchurl {
      url = "https://mediafilez.forgecdn.net/files/4437/745/Enigmatica6ExpertServer-1.8.0.zip";
      sha256 = "sha256-rmMzXGBqKREWKqUqJ8nNfZOyngamfukA15AmUTjKKIY=";
    };
  };
  mp-server-pause-forge-1_16_5 = {
    pname = "mp-server-pause-forge-1_16_5";
    version = "1.1.0";
    src = fetchurl {
      url = "https://www.curseforge.com/api/v1/mods/556491/files/3803691/download";
      sha256 = "sha256-XhfCex4pwFM3TKQtF+1YdYeIPhR+5pITgKoR+BZN6EA=";
    };
  };
  server-starter = {
    pname = "server-starter";
    version = "2.4.0";
    src = fetchurl {
      url = "https://github.com/EnigmaticaModpacks/ServerStarter/releases/download/v2.4.0/serverstarter-2.4.0.jar";
      sha256 = "sha256-cL7Cdx/QACCah3i4RX8jG/jmJEuz2Numu3OcNmLgmbQ=";
    };
  };
}
