[knock]
src.git = "https://github.com/Metalcape/knock"
src.branch = "cooldown"
fetch.github = "Metalcape/knock"

[mp-server-pause-forge-1_16_5]
src.manual = "1.1.0"
fetch.url = "https://www.curseforge.com/api/v1/mods/556491/files/3803691/download"

[server-starter]
src.github = "EnigmaticaModpacks/ServerStarter"
src.prefix = "v"
fetch.url = "https://github.com/EnigmaticaModpacks/ServerStarter/releases/download/v$ver/serverstarter-$ver.jar"

[mcs-enigmatica-6-expert]
src.manual = "1.8.0"
fetch.url = "https://mediafilez.forgecdn.net/files/4437/745/Enigmatica6ExpertServer-1.8.0.zip"

[mcs-enigmatica-9-expert]
src.manual = "1.22.1"
fetch.url = "https://mediafilez.forgecdn.net/files/5356/769/Enigmatica9ExpertServer-1.22.1.zip"

[mcs-dawncraft]
src.manual = "1.28_f2"
fetch.url = "https://mediafilez.forgecdn.net/files/4709/791/DawnCraft+1.28_f2+Serverpack.zip"

[mcs-create-arcane-engineering]
src.manual = "0.1.9.3"
fetch.url = "https://mediafilez.forgecdn.net/files/4852/56/CAEServer1.9.zip"

[forge-server-40-2-9]
src.manual = "40.2.9"
fetch.url = "https://maven.minecraftforge.net/net/minecraftforge/forge/1.18.2-$ver/forge-1.18.2-$ver-installer.jar"

[forge-server-14-23-5-2860]
src.manual = "14.23.5.2860"
fetch.url = "https://maven.minecraftforge.net/net/minecraftforge/forge/1.12.2-$ver/forge-1.12.2-$ver-installer.jar"

[mcs-sevtech-ages]
src.manual = "3.2.3"
fetch.url = "https://mediafilez.forgecdn.net/files/3570/46/SevTech_Ages_Server_3.2.3.zip"

[mod-sponge-changeskin]
src.manual = "3.2"
fetch.url = "https://ci.codemc.io/job/Games647/job/ChangeSkin/474/artifact/sponge/target/ChangeSkinSponge.jar"

[mod-changeskincore]
src.manual = "3.2"
fetch.url = "https://ci.codemc.io/job/Games647/job/ChangeSkin/474/artifact/core/target/ChangeSkinCore.jar"

[mod-forge-spongeforge]
src.manual = "1.12.2-2838-7.4.7"
fetch.url = "https://repo.spongepowered.org/repository/maven-releases/org/spongepowered/spongeforge/$ver/spongeforge-$ver.jar"

[mod-forge-19-2-dynmap]
src.manual = "3.7-beta-4"
fetch.url = "https://mediafilez.forgecdn.net/files/4979/21/Dynmap-3.7-beta-4-forge-1.19.2.jar"

[mod-forge-19-dynmap-blockscan]
src.manual = "3.7-SNAPSHOT"
fetch.url = "https://dynmap.us/builds/DynmapBlockScan/DynmapBlockScan-3.7-SNAPSHOT-forge-1.19.jar"

[mod-forge-19-bluemap]
src.manual = "3.13"
fetch.url = "https://github.com/BlueMap-Minecraft/BlueMap/releases/download/v3.13/BlueMap-3.13-forge-1.19.1.jar"

[mod-forge-18-bluemap]
src.manual = "5.2"
fetch.url = "https://github.com/BlueMap-Minecraft/BlueMap/releases/download/v5.2/BlueMap-5.2-forge-1.18.1.jar"

[mcs-life-in-the-village-3]
src.manual = "2.8"
fetch.url = "https://mediafilez.forgecdn.net/files/5290/323/LITV3-1.19.2-Serverpack-2.8.zip"

[mod-forge-192-corail-tombstone]
src.manual = "8.2.16"
fetch.url = "https://mediafilez.forgecdn.net/files/5202/57/tombstone-1.19.2-8.2.16.jar"

[mod-forge-192-carryon]
src.manual = "2.1.2.23"
fetch.url = "https://mediafilez.forgecdn.net/files/5141/759/carryon-forge-1.19.2-2.1.2.23.jar"

[mod-forge-192-passablefolliage]
src.manual = "5.2.1"
fetch.url = "https://mediafilez.forgecdn.net/files/4542/72/PassableFoliage-1.19.1-forge-5.2.1.jar"

[mod-forge-192-kiwi]
src.manual = "8.3.6"
fetch.url = "https://mediafilez.forgecdn.net/files/5063/293/Kiwi-1.19.2-forge-8.3.6.jar"

[mod-forge-192-ftb-chunks]
src.manual = "1902.4.4"
fetch.url = "https://mediafilez.forgecdn.net/files/5001/266/ftb-chunks-forge-1902.4.4-build.326.jar"

[mod-forge-192-ftb-xmod-compat]
src.manual = "1.2.3"
fetch.url = "https://mediafilez.forgecdn.net/files/4857/341/ftb-xmod-compat-forge-1.2.3.jar"

[mod-forge-182-functional-storage]
src.manual = "1.1.4"
fetch.url = "https://mediafilez.forgecdn.net/files/5271/589/functionalstorage-1.18.2-1.1.4.jar"

[mod-forge-182-easier-sleeping]
src.manual  = "2.1.0"
fetch.url = "https://mediafilez.forgecdn.net/files/3683/922/EasierSleeping-1.18.2-2.1.0.jar"
