# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  "\"4ops.packer\"" = {
    pname = "\"4ops.packer\"";
    version = "0.3.0";
    src = fetchurl {
      url = "https://4ops.gallery.vsassets.io/_apis/public/gallery/publisher/4ops/extension/packer/0.3.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "packer-0.3.0.zip";
      sha256 = "sha256-aYvTxdd+6ESSEDFtb8hwITVjLdbwTV5ZabpwAywGwVc=";
    };
  };
  "\"PKief.material-icon-theme\"" = {
    pname = "\"PKief.material-icon-theme\"";
    version = "4.24.0";
    src = fetchurl {
      url = "https://PKief.gallery.vsassets.io/_apis/public/gallery/publisher/PKief/extension/material-icon-theme/4.24.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "material-icon-theme-4.24.0.zip";
      sha256 = "sha256-hJy+ymnlF9a2vvN/HhJ5N75lIc2afzkq+S0Cv/KnD3M=";
    };
  };
  "\"apollographql.vscode-apollo\"" = {
    pname = "\"apollographql.vscode-apollo\"";
    version = "1.19.11";
    src = fetchurl {
      url = "https://apollographql.gallery.vsassets.io/_apis/public/gallery/publisher/apollographql/extension/vscode-apollo/1.19.11/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-apollo-1.19.11.zip";
      sha256 = "sha256-EixefDuJiw/p5yAR/UQLK1a1RXJLXlTmOlD34qpAN+U=";
    };
  };
  "\"arrterian.nix-env-selector\"" = {
    pname = "\"arrterian.nix-env-selector\"";
    version = "1.0.9";
    src = fetchurl {
      url = "https://arrterian.gallery.vsassets.io/_apis/public/gallery/publisher/arrterian/extension/nix-env-selector/1.0.9/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "nix-env-selector-1.0.9.zip";
      sha256 = "sha256-TkxqWZ8X+PAonzeXQ+sI9WI+XlqUHll7YyM7N9uErk0=";
    };
  };
  "\"bbenoist.nix\"" = {
    pname = "\"bbenoist.nix\"";
    version = "1.0.1";
    src = fetchurl {
      url = "https://bbenoist.gallery.vsassets.io/_apis/public/gallery/publisher/bbenoist/extension/nix/1.0.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "nix-1.0.1.zip";
      sha256 = "sha256-qwxqOGublQeVP2qrLF94ndX/Be9oZOn+ZMCFX1yyoH0=";
    };
  };
  "\"bungcip.better-toml\"" = {
    pname = "\"bungcip.better-toml\"";
    version = "0.3.2";
    src = fetchurl {
      url = "https://bungcip.gallery.vsassets.io/_apis/public/gallery/publisher/bungcip/extension/better-toml/0.3.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "better-toml-0.3.2.zip";
      sha256 = "sha256-g+LfgjAnSuSj/nSmlPdB0t29kqTmegZB5B1cYzP8kCI=";
    };
  };
  "\"christian-kohler.npm-intellisense\"" = {
    pname = "\"christian-kohler.npm-intellisense\"";
    version = "1.4.4";
    src = fetchurl {
      url = "https://christian-kohler.gallery.vsassets.io/_apis/public/gallery/publisher/christian-kohler/extension/npm-intellisense/1.4.4/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "npm-intellisense-1.4.4.zip";
      sha256 = "sha256-RLni/Iz2ZIX8/17gArc90ycVU9wPhNBa32Pe47sdGr0=";
    };
  };
  "\"christian-kohler.path-intellisense\"" = {
    pname = "\"christian-kohler.path-intellisense\"";
    version = "2.8.4";
    src = fetchurl {
      url = "https://christian-kohler.gallery.vsassets.io/_apis/public/gallery/publisher/christian-kohler/extension/path-intellisense/2.8.4/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "path-intellisense-2.8.4.zip";
      sha256 = "sha256-FEBYcjJHOwmxVHhhyxqOpk/V6hvtMkhkvLVpmJCMSZw=";
    };
  };
  "\"coolbear.systemd-unit-file\"" = {
    pname = "\"coolbear.systemd-unit-file\"";
    version = "1.0.6";
    src = fetchurl {
      url = "https://coolbear.gallery.vsassets.io/_apis/public/gallery/publisher/coolbear/extension/systemd-unit-file/1.0.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "systemd-unit-file-1.0.6.zip";
      sha256 = "sha256-ZhxSUT3zqdPNiHnfaDp/LQiGxTSLY1Vpc5zEbpv+gGk=";
    };
  };
  "\"cschlosser.doxdocgen\"" = {
    pname = "\"cschlosser.doxdocgen\"";
    version = "1.4.0";
    src = fetchurl {
      url = "https://cschlosser.gallery.vsassets.io/_apis/public/gallery/publisher/cschlosser/extension/doxdocgen/1.4.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "doxdocgen-1.4.0.zip";
      sha256 = "sha256-InEfF1X7AgtsV47h8WWq5DZh6k/wxYhl2r/pLZz9JbU=";
    };
  };
  "\"davidanson.vscode-markdownlint\"" = {
    pname = "\"davidanson.vscode-markdownlint\"";
    version = "0.49.0";
    src = fetchurl {
      url = "https://davidanson.gallery.vsassets.io/_apis/public/gallery/publisher/davidanson/extension/vscode-markdownlint/0.49.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-markdownlint-0.49.0.zip";
      sha256 = "sha256-Mh/OoRK410aXEr3sK2CYFDsXGSqFT+JOWi9jHOdK01Y=";
    };
  };
  "\"davidnussio.vscode-jq-playground\"" = {
    pname = "\"davidnussio.vscode-jq-playground\"";
    version = "4.3.5";
    src = fetchurl {
      url = "https://davidnussio.gallery.vsassets.io/_apis/public/gallery/publisher/davidnussio/extension/vscode-jq-playground/4.3.5/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-jq-playground-4.3.5.zip";
      sha256 = "sha256-kLpGD8vse4Lx1wbF+yCb+cAGccmibfRKd2cLCelqpJY=";
    };
  };
  "\"dbaeumer.vscode-eslint\"" = {
    pname = "\"dbaeumer.vscode-eslint\"";
    version = "2.4.0";
    src = fetchurl {
      url = "https://dbaeumer.gallery.vsassets.io/_apis/public/gallery/publisher/dbaeumer/extension/vscode-eslint/2.4.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-eslint-2.4.0.zip";
      sha256 = "sha256-7MUQJkLPOF3oO0kpmfP3bWbS3aT7J0RF7f74LW55BQs=";
    };
  };
  "\"donjayamanne.githistory\"" = {
    pname = "\"donjayamanne.githistory\"";
    version = "0.6.20";
    src = fetchurl {
      url = "https://donjayamanne.gallery.vsassets.io/_apis/public/gallery/publisher/donjayamanne/extension/githistory/0.6.20/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "githistory-0.6.20.zip";
      sha256 = "sha256-nEdYS9/cMS4dcbFje23a47QBZr9eDK3dvtkFWqA+OHU=";
    };
  };
  "\"eamodio.gitlens\"" = {
    pname = "\"eamodio.gitlens\"";
    version = "2023.3.1004";
    src = fetchurl {
      url = "https://eamodio.gallery.vsassets.io/_apis/public/gallery/publisher/eamodio/extension/gitlens/2023.3.1004/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "gitlens-2023.3.1004.zip";
      sha256 = "sha256-4Sqrfyx04JvzNgjTCs4f5Nds6y6JxjhpZmn5iZxbg3I=";
    };
  };
  "\"editorconfig.editorconfig\"" = {
    pname = "\"editorconfig.editorconfig\"";
    version = "0.16.4";
    src = fetchurl {
      url = "https://editorconfig.gallery.vsassets.io/_apis/public/gallery/publisher/editorconfig/extension/editorconfig/0.16.4/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "editorconfig-0.16.4.zip";
      sha256 = "sha256-j+P2oprpH0rzqI0VKt0JbZG19EDE7e7+kAb3MGGCRDk=";
    };
  };
  "\"eg2.vscode-npm-script\"" = {
    pname = "\"eg2.vscode-npm-script\"";
    version = "0.3.29";
    src = fetchurl {
      url = "https://eg2.gallery.vsassets.io/_apis/public/gallery/publisher/eg2/extension/vscode-npm-script/0.3.29/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-npm-script-0.3.29.zip";
      sha256 = "sha256-k6DtmhYBj7mg8SUU3pg+ezRzWvhiECqYQVj9LDhhV4I=";
    };
  };
  "\"erd0s.terraform-autocomplete\"" = {
    pname = "\"erd0s.terraform-autocomplete\"";
    version = "0.0.8";
    src = fetchurl {
      url = "https://erd0s.gallery.vsassets.io/_apis/public/gallery/publisher/erd0s/extension/terraform-autocomplete/0.0.8/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "terraform-autocomplete-0.0.8.zip";
      sha256 = "sha256-cAr1PzOq0RokCpSAEFYl/bQjVR1ZwW9L/KPrG6HRR5U=";
    };
  };
  "\"ericadamski.carbon-now-sh\"" = {
    pname = "\"ericadamski.carbon-now-sh\"";
    version = "1.2.0";
    src = fetchurl {
      url = "https://ericadamski.gallery.vsassets.io/_apis/public/gallery/publisher/ericadamski/extension/carbon-now-sh/1.2.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "carbon-now-sh-1.2.0.zip";
      sha256 = "sha256-jFI4tS6vcAPhrN0G6ni0qf2aPtq+INeLsZMN8/vewCo=";
    };
  };
  "\"golang.go\"" = {
    pname = "\"golang.go\"";
    version = "0.38.0";
    src = fetchurl {
      url = "https://golang.gallery.vsassets.io/_apis/public/gallery/publisher/golang/extension/go/0.38.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "go-0.38.0.zip";
      sha256 = "sha256-wOWouVz4mE4BzmgQOLQyVWsMadMqeUkFWHnruxStU0Q=";
    };
  };
  "\"graphql.vscode-graphql\"" = {
    pname = "\"graphql.vscode-graphql\"";
    version = "0.8.6";
    src = fetchurl {
      url = "https://graphql.gallery.vsassets.io/_apis/public/gallery/publisher/graphql/extension/vscode-graphql/0.8.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-graphql-0.8.6.zip";
      sha256 = "sha256-iQWDYdz/TG8pxPEq9RirNtY4kwhpK+gO0It6OTdrM+0=";
    };
  };
  "\"graphql.vscode-graphql-execution\"" = {
    pname = "\"graphql.vscode-graphql-execution\"";
    version = "0.1.8";
    src = fetchurl {
      url = "https://graphql.gallery.vsassets.io/_apis/public/gallery/publisher/graphql/extension/vscode-graphql-execution/0.1.8/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-graphql-execution-0.1.8.zip";
      sha256 = "sha256-Mg2jidiaiQ4+ay/MOA6wVO79a7BeOROXhpm4+pAshFs=";
    };
  };
  "\"graphql.vscode-graphql-syntax\"" = {
    pname = "\"graphql.vscode-graphql-syntax\"";
    version = "1.1.0";
    src = fetchurl {
      url = "https://graphql.gallery.vsassets.io/_apis/public/gallery/publisher/graphql/extension/vscode-graphql-syntax/1.1.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-graphql-syntax-1.1.0.zip";
      sha256 = "sha256-qazU0UyZ9de6Huj2AYZqqBo4jVW/ZQmFJhV7XXAblxo=";
    };
  };
  "\"hashicorp.terraform\"" = {
    pname = "\"hashicorp.terraform\"";
    version = "2.25.4";
    src = fetchurl {
      url = "https://hashicorp.gallery.vsassets.io/_apis/public/gallery/publisher/hashicorp/extension/terraform/2.25.4/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "terraform-2.25.4.zip";
      sha256 = "sha256-oR72zKvjmFjr78KbEbnyyzfB5TeTloQRzmRfVeTEmPc=";
    };
  };
  "\"ipedrazas.kubernetes-snippets\"" = {
    pname = "\"ipedrazas.kubernetes-snippets\"";
    version = "0.1.9";
    src = fetchurl {
      url = "https://ipedrazas.gallery.vsassets.io/_apis/public/gallery/publisher/ipedrazas/extension/kubernetes-snippets/0.1.9/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "kubernetes-snippets-0.1.9.zip";
      sha256 = "sha256-BlPEzRSe2NfRPjyShepa2DEhe1Jgiq7bXk2ze3eqwT0=";
    };
  };
  "\"iterative.dvc\"" = {
    pname = "\"iterative.dvc\"";
    version = "0.6.17";
    src = fetchurl {
      url = "https://iterative.gallery.vsassets.io/_apis/public/gallery/publisher/iterative/extension/dvc/0.6.17/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "dvc-0.6.17.zip";
      sha256 = "sha256-fu+RwabqzS79cmdYG0X5scA3PU9ay8uAP2wXFVIMuMk=";
    };
  };
  "\"ivory-lab.jenkinsfile-support\"" = {
    pname = "\"ivory-lab.jenkinsfile-support\"";
    version = "1.1.0";
    src = fetchurl {
      url = "https://ivory-lab.gallery.vsassets.io/_apis/public/gallery/publisher/ivory-lab/extension/jenkinsfile-support/1.1.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "jenkinsfile-support-1.1.0.zip";
      sha256 = "sha256-amW9jFeA4YVi8iN7pEOUCU0QA9fANtB7DlnMz9AEolQ=";
    };
  };
  "\"janjoerke.jenkins-pipeline-linter-connector\"" = {
    pname = "\"janjoerke.jenkins-pipeline-linter-connector\"";
    version = "1.2.0";
    src = fetchurl {
      url = "https://janjoerke.gallery.vsassets.io/_apis/public/gallery/publisher/janjoerke/extension/jenkins-pipeline-linter-connector/1.2.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "jenkins-pipeline-linter-connector-1.2.0.zip";
      sha256 = "sha256-L+rMNS/pNseioBqVbUrLdd/m5wpzrYfeLhoyJUcIYAM=";
    };
  };
  "\"jeff-hykin.better-cpp-syntax\"" = {
    pname = "\"jeff-hykin.better-cpp-syntax\"";
    version = "1.17.2";
    src = fetchurl {
      url = "https://jeff-hykin.gallery.vsassets.io/_apis/public/gallery/publisher/jeff-hykin/extension/better-cpp-syntax/1.17.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "better-cpp-syntax-1.17.2.zip";
      sha256 = "sha256-p3SKu9FbtuP6in2dSsr5a0aB5W+YNQ0kMgMJoDYrhcU=";
    };
  };
  "\"jnoortheen.nix-ide\"" = {
    pname = "\"jnoortheen.nix-ide\"";
    version = "0.2.1";
    src = fetchurl {
      url = "https://jnoortheen.gallery.vsassets.io/_apis/public/gallery/publisher/jnoortheen/extension/nix-ide/0.2.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "nix-ide-0.2.1.zip";
      sha256 = "sha256-yC4ybThMFA2ncGhp8BYD7IrwYiDU3226hewsRvJYKy4=";
    };
  };
  "\"josetr.cmake-language-support-vscode\"" = {
    pname = "\"josetr.cmake-language-support-vscode\"";
    version = "0.0.9";
    src = fetchurl {
      url = "https://josetr.gallery.vsassets.io/_apis/public/gallery/publisher/josetr/extension/cmake-language-support-vscode/0.0.9/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "cmake-language-support-vscode-0.0.9.zip";
      sha256 = "sha256-LNtXYZ65Lka1lpxeKozK6LB0yaxAjHsfVsCJ8ILX8io=";
    };
  };
  "\"jq-syntax-highlighting.jq-syntax-highlighting\"" = {
    pname = "\"jq-syntax-highlighting.jq-syntax-highlighting\"";
    version = "0.0.2";
    src = fetchurl {
      url = "https://jq-syntax-highlighting.gallery.vsassets.io/_apis/public/gallery/publisher/jq-syntax-highlighting/extension/jq-syntax-highlighting/0.0.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "jq-syntax-highlighting-0.0.2.zip";
      sha256 = "sha256-Bwq+aZuDmzjHw+ZnIWlL4aGz6UnqxaKm5WUko0yuIWE=";
    };
  };
  "\"kamadorueda.alejandra\"" = {
    pname = "\"kamadorueda.alejandra\"";
    version = "1.0.0";
    src = fetchurl {
      url = "https://kamadorueda.gallery.vsassets.io/_apis/public/gallery/publisher/kamadorueda/extension/alejandra/1.0.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "alejandra-1.0.0.zip";
      sha256 = "sha256-COlEjKhm8tK5XfOjrpVUDQ7x3JaOLiYoZ4MdwTL8ktk=";
    };
  };
  "\"lunuan.kubernetes-templates\"" = {
    pname = "\"lunuan.kubernetes-templates\"";
    version = "1.3.1";
    src = fetchurl {
      url = "https://lunuan.gallery.vsassets.io/_apis/public/gallery/publisher/lunuan/extension/kubernetes-templates/1.3.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "kubernetes-templates-1.3.1.zip";
      sha256 = "sha256-1XS28VLbdSQjAAnCrvid/aE8GA2WReB9Roa6E3PqXi4=";
    };
  };
  "\"maarti.jenkins-doc\"" = {
    pname = "\"maarti.jenkins-doc\"";
    version = "1.7.0";
    src = fetchurl {
      url = "https://maarti.gallery.vsassets.io/_apis/public/gallery/publisher/maarti/extension/jenkins-doc/1.7.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "jenkins-doc-1.7.0.zip";
      sha256 = "sha256-/1u83+dWFeyV+Q3P4yAO6CvigBS6rh7KN1oPCM7vzPs=";
    };
  };
  "\"mads-hartmann.bash-ide-vscode\"" = {
    pname = "\"mads-hartmann.bash-ide-vscode\"";
    version = "1.35.0";
    src = fetchurl {
      url = "https://mads-hartmann.gallery.vsassets.io/_apis/public/gallery/publisher/mads-hartmann/extension/bash-ide-vscode/1.35.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "bash-ide-vscode-1.35.0.zip";
      sha256 = "sha256-lEwzlvyKczKI3bE6xFPBm3so+Ob3TvqgRr0D4+UX7WI=";
    };
  };
  "\"ms-azuretools.vscode-docker\"" = {
    pname = "\"ms-azuretools.vscode-docker\"";
    version = "1.24.0";
    src = fetchurl {
      url = "https://ms-azuretools.gallery.vsassets.io/_apis/public/gallery/publisher/ms-azuretools/extension/vscode-docker/1.24.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-docker-1.24.0.zip";
      sha256 = "sha256-zZ34KQrRPqVbfGdpYACuLMiMj4ZIWSnJIPac1yXD87k=";
    };
  };
  "\"ms-dotnettools.vscode-dotnet-runtime\"" = {
    pname = "\"ms-dotnettools.vscode-dotnet-runtime\"";
    version = "1.6.0";
    src = fetchurl {
      url = "https://ms-dotnettools.gallery.vsassets.io/_apis/public/gallery/publisher/ms-dotnettools/extension/vscode-dotnet-runtime/1.6.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-dotnet-runtime-1.6.0.zip";
      sha256 = "sha256-A3m5IvPKgmF2Dix1/bHFGcrJYriYsFgRagkZNcWf/RA=";
    };
  };
  "\"ms-kubernetes-tools.vscode-kubernetes-tools\"" = {
    pname = "\"ms-kubernetes-tools.vscode-kubernetes-tools\"";
    version = "1.3.11";
    src = fetchurl {
      url = "https://ms-kubernetes-tools.gallery.vsassets.io/_apis/public/gallery/publisher/ms-kubernetes-tools/extension/vscode-kubernetes-tools/1.3.11/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-kubernetes-tools-1.3.11.zip";
      sha256 = "sha256-I2ud9d4VtgiiIT0MeoaMThgjLYtSuftFVZHVJTMlJ8s=";
    };
  };
  "\"ms-python.isort\"" = {
    pname = "\"ms-python.isort\"";
    version = "2023.9.10591013";
    src = fetchurl {
      url = "https://ms-python.gallery.vsassets.io/_apis/public/gallery/publisher/ms-python/extension/isort/2023.9.10591013/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "isort-2023.9.10591013.zip";
      sha256 = "sha256-JUbawqpXOEbNBIfgR6M5MX+bLDyJn+33oNv+TgGTotE=";
    };
  };
  "\"ms-python.python\"" = {
    pname = "\"ms-python.python\"";
    version = "2023.5.10681722";
    src = fetchurl {
      url = "https://ms-python.gallery.vsassets.io/_apis/public/gallery/publisher/ms-python/extension/python/2023.5.10681722/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "python-2023.5.10681722.zip";
      sha256 = "sha256-inhwl006U/wcrVOJqvgrep0q0+sjAgboZv1sZOKCQsI=";
    };
  };
  "\"ms-python.vscode-pylance\"" = {
    pname = "\"ms-python.vscode-pylance\"";
    version = "2023.3.21";
    src = fetchurl {
      url = "https://ms-python.gallery.vsassets.io/_apis/public/gallery/publisher/ms-python/extension/vscode-pylance/2023.3.21/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-pylance-2023.3.21.zip";
      sha256 = "sha256-A49/m3YL9Hy7AGvYrCnZ7GT4VLIqKka4GLsFEytjCUY=";
    };
  };
  "\"ms-toolsai.jupyter\"" = {
    pname = "\"ms-toolsai.jupyter\"";
    version = "2023.3.1000711009";
    src = fetchurl {
      url = "https://ms-toolsai.gallery.vsassets.io/_apis/public/gallery/publisher/ms-toolsai/extension/jupyter/2023.3.1000711009/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "jupyter-2023.3.1000711009.zip";
      sha256 = "sha256-uHwXDN+PCafE6QmpDc0GyUkevSeOA6Bq+x3SsPQA7Vs=";
    };
  };
  "\"ms-toolsai.jupyter-keymap\"" = {
    pname = "\"ms-toolsai.jupyter-keymap\"";
    version = "1.1.0";
    src = fetchurl {
      url = "https://ms-toolsai.gallery.vsassets.io/_apis/public/gallery/publisher/ms-toolsai/extension/jupyter-keymap/1.1.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "jupyter-keymap-1.1.0.zip";
      sha256 = "sha256-krDtR+ZJiJf1Kxcu5mdXOaSAiJb2bXC1H0XWWviWeMQ=";
    };
  };
  "\"ms-toolsai.jupyter-renderers\"" = {
    pname = "\"ms-toolsai.jupyter-renderers\"";
    version = "1.0.15";
    src = fetchurl {
      url = "https://ms-toolsai.gallery.vsassets.io/_apis/public/gallery/publisher/ms-toolsai/extension/jupyter-renderers/1.0.15/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "jupyter-renderers-1.0.15.zip";
      sha256 = "sha256-JR6PunvRRTsSqjSGGAn/1t1B+Ia6X0MgqahehcuSNYA=";
    };
  };
  "\"ms-toolsai.vscode-jupyter-cell-tags\"" = {
    pname = "\"ms-toolsai.vscode-jupyter-cell-tags\"";
    version = "0.1.6";
    src = fetchurl {
      url = "https://ms-toolsai.gallery.vsassets.io/_apis/public/gallery/publisher/ms-toolsai/extension/vscode-jupyter-cell-tags/0.1.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-jupyter-cell-tags-0.1.6.zip";
      sha256 = "sha256-YW7Nv3maqPCyZ/f05XbHjzbao6I8Wtr8DHQhNYH6Y+k=";
    };
  };
  "\"ms-toolsai.vscode-jupyter-slideshow\"" = {
    pname = "\"ms-toolsai.vscode-jupyter-slideshow\"";
    version = "0.1.5";
    src = fetchurl {
      url = "https://ms-toolsai.gallery.vsassets.io/_apis/public/gallery/publisher/ms-toolsai/extension/vscode-jupyter-slideshow/0.1.5/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-jupyter-slideshow-0.1.5.zip";
      sha256 = "sha256-J/pPn+MK/NQX+P+7I178S9G7Uyop4s6Hi33z/ecu2dw=";
    };
  };
  "\"ms-vscode-remote.remote-containers\"" = {
    pname = "\"ms-vscode-remote.remote-containers\"";
    version = "0.283.0";
    src = fetchurl {
      url = "https://ms-vscode-remote.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode-remote/extension/remote-containers/0.283.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "remote-containers-0.283.0.zip";
      sha256 = "sha256-LaZzDLfQHFaOnkvKzq0vmUvAi+Q6sJrJPlAhWX0fY40=";
    };
  };
  "\"ms-vscode-remote.remote-ssh\"" = {
    pname = "\"ms-vscode-remote.remote-ssh\"";
    version = "0.99.2023030315";
    src = fetchurl {
      url = "https://ms-vscode-remote.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode-remote/extension/remote-ssh/0.99.2023030315/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "remote-ssh-0.99.2023030315.zip";
      sha256 = "sha256-ORnjrwilx6wP+xjZY4bDStm6Nj5/PYInbi3Q/qr/KSI=";
    };
  };
  "\"ms-vscode-remote.remote-ssh-edit\"" = {
    pname = "\"ms-vscode-remote.remote-ssh-edit\"";
    version = "0.84.0";
    src = fetchurl {
      url = "https://ms-vscode-remote.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode-remote/extension/remote-ssh-edit/0.84.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "remote-ssh-edit-0.84.0.zip";
      sha256 = "sha256-33jHWC8K0TWJG54m6FqnYEotKqNxkcd/D14TFz6dgmc=";
    };
  };
  "\"ms-vscode-remote.remote-wsl\"" = {
    pname = "\"ms-vscode-remote.remote-wsl\"";
    version = "0.76.1";
    src = fetchurl {
      url = "https://ms-vscode-remote.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode-remote/extension/remote-wsl/0.76.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "remote-wsl-0.76.1.zip";
      sha256 = "sha256-ijMDQ0gmgzNBgNNsvUh5v0kX5NEIdWiX/2344LfmcCw=";
    };
  };
  "\"ms-vscode-remote.vscode-remote-extensionpack\"" = {
    pname = "\"ms-vscode-remote.vscode-remote-extensionpack\"";
    version = "0.24.0";
    src = fetchurl {
      url = "https://ms-vscode-remote.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode-remote/extension/vscode-remote-extensionpack/0.24.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-remote-extensionpack-0.24.0.zip";
      sha256 = "sha256-6v4JWpyMxqTDIjEOL3w25bdTN+3VPFH7HdaSbgIlCmo=";
    };
  };
  "\"ms-vscode.cmake-tools\"" = {
    pname = "\"ms-vscode.cmake-tools\"";
    version = "1.14.15";
    src = fetchurl {
      url = "https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/cmake-tools/1.14.15/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "cmake-tools-1.14.15.zip";
      sha256 = "sha256-Fo6G17FAZxCJ/r5MxMcD2WuSgGuAe45Y64fOKfPQNM4=";
    };
  };
  "\"ms-vscode.cpptools-extension-pack\"" = {
    pname = "\"ms-vscode.cpptools-extension-pack\"";
    version = "1.3.0";
    src = fetchurl {
      url = "https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/cpptools-extension-pack/1.3.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "cpptools-extension-pack-1.3.0.zip";
      sha256 = "sha256-rHST7CYCVins3fqXC+FYiS5Xgcjmi7QW7M4yFrUR04U=";
    };
  };
  "\"ms-vscode.cpptools-themes\"" = {
    pname = "\"ms-vscode.cpptools-themes\"";
    version = "2.0.0";
    src = fetchurl {
      url = "https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/cpptools-themes/2.0.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "cpptools-themes-2.0.0.zip";
      sha256 = "sha256-YWA5UsA+cgvI66uB9d9smwghmsqf3vZPFNpSCK+DJxc=";
    };
  };
  "\"ms-vscode.makefile-tools\"" = {
    pname = "\"ms-vscode.makefile-tools\"";
    version = "0.6.0";
    src = fetchurl {
      url = "https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/makefile-tools/0.6.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "makefile-tools-0.6.0.zip";
      sha256 = "sha256-Sd1bLdRBdLVK8y09wL/CJF+/kThPTH8MHw2mFQt+6h8=";
    };
  };
  "\"natqe.reload\"" = {
    pname = "\"natqe.reload\"";
    version = "0.0.6";
    src = fetchurl {
      url = "https://natqe.gallery.vsassets.io/_apis/public/gallery/publisher/natqe/extension/reload/0.0.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "reload-0.0.6.zip";
      sha256 = "sha256-bTFLk3sCJb7ztkC/Cxci6n7RbcyNjEYNKREUf9wDQRU=";
    };
  };
  "\"nelite.vscode-anime-motivator\"" = {
    pname = "\"nelite.vscode-anime-motivator\"";
    version = "1.0.0";
    src = fetchurl {
      url = "https://nelite.gallery.vsassets.io/_apis/public/gallery/publisher/nelite/extension/vscode-anime-motivator/1.0.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-anime-motivator-1.0.0.zip";
      sha256 = "sha256-bQlZzACE4cl/8FnIcCMRk+UkIb7HztW+gYpfR1T+DCk=";
    };
  };
  "\"nicolasvuillamy.vscode-groovy-lint\"" = {
    pname = "\"nicolasvuillamy.vscode-groovy-lint\"";
    version = "2.0.0";
    src = fetchurl {
      url = "https://nicolasvuillamy.gallery.vsassets.io/_apis/public/gallery/publisher/nicolasvuillamy/extension/vscode-groovy-lint/2.0.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-groovy-lint-2.0.0.zip";
      sha256 = "sha256-iHEIbxXdPQbT2gRu1fUxKOzu/GEpBFwsw4k+lLdVVIc=";
    };
  };
  "\"octref.vetur\"" = {
    pname = "\"octref.vetur\"";
    version = "0.37.3";
    src = fetchurl {
      url = "https://octref.gallery.vsassets.io/_apis/public/gallery/publisher/octref/extension/vetur/0.37.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vetur-0.37.3.zip";
      sha256 = "sha256-3hi1LOZto5AYaomB9ihkAt4j/mhkCDJ8Jqa16piwHIQ=";
    };
  };
  "\"platformio.platformio-ide\"" = {
    pname = "\"platformio.platformio-ide\"";
    version = "3.0.1";
    src = fetchurl {
      url = "https://platformio.gallery.vsassets.io/_apis/public/gallery/publisher/platformio/extension/platformio-ide/3.0.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "platformio-ide-3.0.1.zip";
      sha256 = "sha256-Irf6cibL30dqCbWeJJ+jrUCQFUdhV7XghwKkKdswHQQ=";
    };
  };
  "\"plorefice.devicetree\"" = {
    pname = "\"plorefice.devicetree\"";
    version = "0.1.1";
    src = fetchurl {
      url = "https://plorefice.gallery.vsassets.io/_apis/public/gallery/publisher/plorefice/extension/devicetree/0.1.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "devicetree-0.1.1.zip";
      sha256 = "sha256-udyeY8OuI9+c26WMR63NqElyJLxdMqgOXkkmWF8233k=";
    };
  };
  "\"redhat.java\"" = {
    pname = "\"redhat.java\"";
    version = "1.16.2023030903";
    src = fetchurl {
      url = "https://redhat.gallery.vsassets.io/_apis/public/gallery/publisher/redhat/extension/java/1.16.2023030903/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "java-1.16.2023030903.zip";
      sha256 = "sha256-2bgcW/L/ziGMmpkeO5f389Qu7E/Nw3+HoeQxnH8/XOc=";
    };
  };
  "\"redhat.vscode-commons\"" = {
    pname = "\"redhat.vscode-commons\"";
    version = "0.0.6";
    src = fetchurl {
      url = "https://redhat.gallery.vsassets.io/_apis/public/gallery/publisher/redhat/extension/vscode-commons/0.0.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-commons-0.0.6.zip";
      sha256 = "sha256-tqjGKrQ6fhjco7/sgh2jaJCpikXyzeCOkHM8nRekFq0=";
    };
  };
  "\"redhat.vscode-xml\"" = {
    pname = "\"redhat.vscode-xml\"";
    version = "0.25.2023031003";
    src = fetchurl {
      url = "https://redhat.gallery.vsassets.io/_apis/public/gallery/publisher/redhat/extension/vscode-xml/0.25.2023031003/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-xml-0.25.2023031003.zip";
      sha256 = "sha256-p7AxwkcNeV/HjQrbaDDS626SYGpq9d4UmqLWTbze8ns=";
    };
  };
  "\"redhat.vscode-yaml\"" = {
    pname = "\"redhat.vscode-yaml\"";
    version = "1.12.1";
    src = fetchurl {
      url = "https://redhat.gallery.vsassets.io/_apis/public/gallery/publisher/redhat/extension/vscode-yaml/1.12.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-yaml-1.12.1.zip";
      sha256 = "sha256-wUd21QuZNbG/MQ75SDF+IVd2g2xTj45UMmDkYwJzS7c=";
    };
  };
  "\"roscop.activefileinstatusbar\"" = {
    pname = "\"roscop.activefileinstatusbar\"";
    version = "1.0.3";
    src = fetchurl {
      url = "https://roscop.gallery.vsassets.io/_apis/public/gallery/publisher/roscop/extension/activefileinstatusbar/1.0.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "activefileinstatusbar-1.0.3.zip";
      sha256 = "sha256-5GJODdKL8949a8KR2O7hGsRgAknfPyNEJ+9aiEYYemk=";
    };
  };
  "\"tabeyti.jenkins-jack\"" = {
    pname = "\"tabeyti.jenkins-jack\"";
    version = "1.2.1";
    src = fetchurl {
      url = "https://tabeyti.gallery.vsassets.io/_apis/public/gallery/publisher/tabeyti/extension/jenkins-jack/1.2.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "jenkins-jack-1.2.1.zip";
      sha256 = "sha256-CF2jj8qGzF3gdKT92I0sLh4TuYPHplrwgCGb1VChqgs=";
    };
  };
  "\"tim-koehler.helm-intellisense\"" = {
    pname = "\"tim-koehler.helm-intellisense\"";
    version = "0.14.3";
    src = fetchurl {
      url = "https://tim-koehler.gallery.vsassets.io/_apis/public/gallery/publisher/tim-koehler/extension/helm-intellisense/0.14.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "helm-intellisense-0.14.3.zip";
      sha256 = "sha256-TcXn8n6mKEFpnP8dyv+nXBjsyfUfJNgdL9iSZwA5eo0=";
    };
  };
  "\"twxs.cmake\"" = {
    pname = "\"twxs.cmake\"";
    version = "0.0.17";
    src = fetchurl {
      url = "https://twxs.gallery.vsassets.io/_apis/public/gallery/publisher/twxs/extension/cmake/0.0.17/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "cmake-0.0.17.zip";
      sha256 = "sha256-CFiva1AO/oHpszbpd7lLtDzbv1Yi55yQOQPP/kCTH4Y=";
    };
  };
  "\"visualstudioexptteam.intellicode-api-usage-examples\"" = {
    pname = "\"visualstudioexptteam.intellicode-api-usage-examples\"";
    version = "0.2.7";
    src = fetchurl {
      url = "https://visualstudioexptteam.gallery.vsassets.io/_apis/public/gallery/publisher/visualstudioexptteam/extension/intellicode-api-usage-examples/0.2.7/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "intellicode-api-usage-examples-0.2.7.zip";
      sha256 = "sha256-SJN5w9DCtGaCXCXXtUMhdwuajd9Az01oqHdBQ9KeQyc=";
    };
  };
  "\"visualstudioexptteam.vscodeintellicode\"" = {
    pname = "\"visualstudioexptteam.vscodeintellicode\"";
    version = "1.2.30";
    src = fetchurl {
      url = "https://visualstudioexptteam.gallery.vsassets.io/_apis/public/gallery/publisher/visualstudioexptteam/extension/vscodeintellicode/1.2.30/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscodeintellicode-1.2.30.zip";
      sha256 = "sha256-f2Gn+W0QHN8jD5aCG+P93Y+JDr/vs2ldGL7uQwBK4lE=";
    };
  };
  "\"vscjava.vscode-java-debug\"" = {
    pname = "\"vscjava.vscode-java-debug\"";
    version = "0.49.2023022723";
    src = fetchurl {
      url = "https://vscjava.gallery.vsassets.io/_apis/public/gallery/publisher/vscjava/extension/vscode-java-debug/0.49.2023022723/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-java-debug-0.49.2023022723.zip";
      sha256 = "sha256-DeG3LQk1PREso7qOG0oUrocD2kzRwO5F6qpLVYwm4R8=";
    };
  };
  "\"vscjava.vscode-java-dependency\"" = {
    pname = "\"vscjava.vscode-java-dependency\"";
    version = "0.21.2023030900";
    src = fetchurl {
      url = "https://vscjava.gallery.vsassets.io/_apis/public/gallery/publisher/vscjava/extension/vscode-java-dependency/0.21.2023030900/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-java-dependency-0.21.2023030900.zip";
      sha256 = "sha256-uvXEWHfHiIXIWo2E920mBHyLCIDPgRJubLv60FObTyY=";
    };
  };
  "\"vscjava.vscode-java-pack\"" = {
    pname = "\"vscjava.vscode-java-pack\"";
    version = "0.25.2023021400";
    src = fetchurl {
      url = "https://vscjava.gallery.vsassets.io/_apis/public/gallery/publisher/vscjava/extension/vscode-java-pack/0.25.2023021400/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-java-pack-0.25.2023021400.zip";
      sha256 = "sha256-2eTQyEXpH9nYjV+eFDajfv0X2SqEge9p86StZpVxyEw=";
    };
  };
  "\"vscjava.vscode-java-test\"" = {
    pname = "\"vscjava.vscode-java-test\"";
    version = "0.38.2023030203";
    src = fetchurl {
      url = "https://vscjava.gallery.vsassets.io/_apis/public/gallery/publisher/vscjava/extension/vscode-java-test/0.38.2023030203/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-java-test-0.38.2023030203.zip";
      sha256 = "sha256-rKuNH7kBx8Cpsd48KOsmd09eh7bJ78VG0P96lYxQXt0=";
    };
  };
  "\"vscjava.vscode-maven\"" = {
    pname = "\"vscjava.vscode-maven\"";
    version = "0.40.2023030703";
    src = fetchurl {
      url = "https://vscjava.gallery.vsassets.io/_apis/public/gallery/publisher/vscjava/extension/vscode-maven/0.40.2023030703/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-maven-0.40.2023030703.zip";
      sha256 = "sha256-FdvB/phVSWWW2xu/A+K+ijfZxD4I6gJUD0li5PvcvyI=";
    };
  };
  "\"whi-tw.klipper-config-syntax\"" = {
    pname = "\"whi-tw.klipper-config-syntax\"";
    version = "0.2.1";
    src = fetchurl {
      url = "https://whi-tw.gallery.vsassets.io/_apis/public/gallery/publisher/whi-tw/extension/klipper-config-syntax/0.2.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "klipper-config-syntax-0.2.1.zip";
      sha256 = "sha256-SxhLPltowAdgfKaAqaCRxaJ2qmaGFN/8j0Hcr2v8ffg=";
    };
  };
  "\"xadillax.viml\"" = {
    pname = "\"xadillax.viml\"";
    version = "2.1.2";
    src = fetchurl {
      url = "https://xadillax.gallery.vsassets.io/_apis/public/gallery/publisher/xadillax/extension/viml/2.1.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "viml-2.1.2.zip";
      sha256 = "sha256-n91Rj1Rpp7j7gndkt0bV+jT1nRMv7+coVoSL5c7Ii3A=";
    };
  };
  "\"yzane.markdown-pdf\"" = {
    pname = "\"yzane.markdown-pdf\"";
    version = "1.4.4";
    src = fetchurl {
      url = "https://yzane.gallery.vsassets.io/_apis/public/gallery/publisher/yzane/extension/markdown-pdf/1.4.4/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "markdown-pdf-1.4.4.zip";
      sha256 = "sha256-Tt1UF1i7bgWm/jRP6IG5UOQcfe5YOeCx6Hxs/bnkkgE=";
    };
  };
}
