# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  "\"4ops.packer\"" = {
    pname = "\"4ops.packer\"";
    version = "0.3.0";
    src = fetchurl {
      url = "https://4ops.gallery.vsassets.io/_apis/public/gallery/publisher/4ops/extension/packer/0.3.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "packer-0.3.0.zip";
      sha256 = "sha256-aYvTxdd+6ESSEDFtb8hwITVjLdbwTV5ZabpwAywGwVc=";
    };
  };
  "\"PKief.material-icon-theme\"" = {
    pname = "\"PKief.material-icon-theme\"";
    version = "4.23.1";
    src = fetchurl {
      url = "https://PKief.gallery.vsassets.io/_apis/public/gallery/publisher/PKief/extension/material-icon-theme/4.23.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "material-icon-theme-4.23.1.zip";
      sha256 = "sha256-BfKS6p36CfMAxPKkwC+04wurenq4XBkvj21u/NJh4Js=";
    };
  };
  "\"apollographql.vscode-apollo\"" = {
    pname = "\"apollographql.vscode-apollo\"";
    version = "1.19.11";
    src = fetchurl {
      url = "https://apollographql.gallery.vsassets.io/_apis/public/gallery/publisher/apollographql/extension/vscode-apollo/1.19.11/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-apollo-1.19.11.zip";
      sha256 = "sha256-EixefDuJiw/p5yAR/UQLK1a1RXJLXlTmOlD34qpAN+U=";
    };
  };
  "\"arrterian.nix-env-selector\"" = {
    pname = "\"arrterian.nix-env-selector\"";
    version = "1.0.9";
    src = fetchurl {
      url = "https://arrterian.gallery.vsassets.io/_apis/public/gallery/publisher/arrterian/extension/nix-env-selector/1.0.9/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "nix-env-selector-1.0.9.zip";
      sha256 = "sha256-TkxqWZ8X+PAonzeXQ+sI9WI+XlqUHll7YyM7N9uErk0=";
    };
  };
  "\"bbenoist.nix\"" = {
    pname = "\"bbenoist.nix\"";
    version = "1.0.1";
    src = fetchurl {
      url = "https://bbenoist.gallery.vsassets.io/_apis/public/gallery/publisher/bbenoist/extension/nix/1.0.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "nix-1.0.1.zip";
      sha256 = "sha256-qwxqOGublQeVP2qrLF94ndX/Be9oZOn+ZMCFX1yyoH0=";
    };
  };
  "\"bungcip.better-toml\"" = {
    pname = "\"bungcip.better-toml\"";
    version = "0.3.2";
    src = fetchurl {
      url = "https://bungcip.gallery.vsassets.io/_apis/public/gallery/publisher/bungcip/extension/better-toml/0.3.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "better-toml-0.3.2.zip";
      sha256 = "sha256-g+LfgjAnSuSj/nSmlPdB0t29kqTmegZB5B1cYzP8kCI=";
    };
  };
  "\"christian-kohler.npm-intellisense\"" = {
    pname = "\"christian-kohler.npm-intellisense\"";
    version = "1.4.4";
    src = fetchurl {
      url = "https://christian-kohler.gallery.vsassets.io/_apis/public/gallery/publisher/christian-kohler/extension/npm-intellisense/1.4.4/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "npm-intellisense-1.4.4.zip";
      sha256 = "sha256-RLni/Iz2ZIX8/17gArc90ycVU9wPhNBa32Pe47sdGr0=";
    };
  };
  "\"christian-kohler.path-intellisense\"" = {
    pname = "\"christian-kohler.path-intellisense\"";
    version = "2.8.4";
    src = fetchurl {
      url = "https://christian-kohler.gallery.vsassets.io/_apis/public/gallery/publisher/christian-kohler/extension/path-intellisense/2.8.4/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "path-intellisense-2.8.4.zip";
      sha256 = "sha256-FEBYcjJHOwmxVHhhyxqOpk/V6hvtMkhkvLVpmJCMSZw=";
    };
  };
  "\"coolbear.systemd-unit-file\"" = {
    pname = "\"coolbear.systemd-unit-file\"";
    version = "1.0.6";
    src = fetchurl {
      url = "https://coolbear.gallery.vsassets.io/_apis/public/gallery/publisher/coolbear/extension/systemd-unit-file/1.0.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "systemd-unit-file-1.0.6.zip";
      sha256 = "sha256-ZhxSUT3zqdPNiHnfaDp/LQiGxTSLY1Vpc5zEbpv+gGk=";
    };
  };
  "\"cschlosser.doxdocgen\"" = {
    pname = "\"cschlosser.doxdocgen\"";
    version = "1.4.0";
    src = fetchurl {
      url = "https://cschlosser.gallery.vsassets.io/_apis/public/gallery/publisher/cschlosser/extension/doxdocgen/1.4.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "doxdocgen-1.4.0.zip";
      sha256 = "sha256-InEfF1X7AgtsV47h8WWq5DZh6k/wxYhl2r/pLZz9JbU=";
    };
  };
  "\"davidanson.vscode-markdownlint\"" = {
    pname = "\"davidanson.vscode-markdownlint\"";
    version = "0.49.0";
    src = fetchurl {
      url = "https://davidanson.gallery.vsassets.io/_apis/public/gallery/publisher/davidanson/extension/vscode-markdownlint/0.49.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-markdownlint-0.49.0.zip";
      sha256 = "sha256-Mh/OoRK410aXEr3sK2CYFDsXGSqFT+JOWi9jHOdK01Y=";
    };
  };
  "\"davidnussio.vscode-jq-playground\"" = {
    pname = "\"davidnussio.vscode-jq-playground\"";
    version = "4.3.5";
    src = fetchurl {
      url = "https://davidnussio.gallery.vsassets.io/_apis/public/gallery/publisher/davidnussio/extension/vscode-jq-playground/4.3.5/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-jq-playground-4.3.5.zip";
      sha256 = "sha256-kLpGD8vse4Lx1wbF+yCb+cAGccmibfRKd2cLCelqpJY=";
    };
  };
  "\"dbaeumer.vscode-eslint\"" = {
    pname = "\"dbaeumer.vscode-eslint\"";
    version = "2.3.3";
    src = fetchurl {
      url = "https://dbaeumer.gallery.vsassets.io/_apis/public/gallery/publisher/dbaeumer/extension/vscode-eslint/2.3.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-eslint-2.3.3.zip";
      sha256 = "sha256-T+EItTtiWw2GQEmYz8qkKl3jhC2mHwdP2XUt5/j6Ic8=";
    };
  };
  "\"donjayamanne.githistory\"" = {
    pname = "\"donjayamanne.githistory\"";
    version = "0.6.19";
    src = fetchurl {
      url = "https://donjayamanne.gallery.vsassets.io/_apis/public/gallery/publisher/donjayamanne/extension/githistory/0.6.19/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "githistory-0.6.19.zip";
      sha256 = "sha256-YyEr4XRI2zzkzDXX2oS+jVnm5dggoZcS4Vc8mNSuQpc=";
    };
  };
  "\"eamodio.gitlens\"" = {
    pname = "\"eamodio.gitlens\"";
    version = "2023.1.2804";
    src = fetchurl {
      url = "https://eamodio.gallery.vsassets.io/_apis/public/gallery/publisher/eamodio/extension/gitlens/2023.1.2804/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "gitlens-2023.1.2804.zip";
      sha256 = "sha256-YvL60xvlZfYvvOKVxrGNoXwsVu308EWtEYOuvpSIwTs=";
    };
  };
  "\"editorconfig.editorconfig\"" = {
    pname = "\"editorconfig.editorconfig\"";
    version = "0.16.4";
    src = fetchurl {
      url = "https://editorconfig.gallery.vsassets.io/_apis/public/gallery/publisher/editorconfig/extension/editorconfig/0.16.4/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "editorconfig-0.16.4.zip";
      sha256 = "sha256-j+P2oprpH0rzqI0VKt0JbZG19EDE7e7+kAb3MGGCRDk=";
    };
  };
  "\"eg2.vscode-npm-script\"" = {
    pname = "\"eg2.vscode-npm-script\"";
    version = "0.3.29";
    src = fetchurl {
      url = "https://eg2.gallery.vsassets.io/_apis/public/gallery/publisher/eg2/extension/vscode-npm-script/0.3.29/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-npm-script-0.3.29.zip";
      sha256 = "sha256-k6DtmhYBj7mg8SUU3pg+ezRzWvhiECqYQVj9LDhhV4I=";
    };
  };
  "\"erd0s.terraform-autocomplete\"" = {
    pname = "\"erd0s.terraform-autocomplete\"";
    version = "0.0.8";
    src = fetchurl {
      url = "https://erd0s.gallery.vsassets.io/_apis/public/gallery/publisher/erd0s/extension/terraform-autocomplete/0.0.8/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "terraform-autocomplete-0.0.8.zip";
      sha256 = "sha256-cAr1PzOq0RokCpSAEFYl/bQjVR1ZwW9L/KPrG6HRR5U=";
    };
  };
  "\"golang.go\"" = {
    pname = "\"golang.go\"";
    version = "0.37.1";
    src = fetchurl {
      url = "https://golang.gallery.vsassets.io/_apis/public/gallery/publisher/golang/extension/go/0.37.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "go-0.37.1.zip";
      sha256 = "sha256-xOiMVUkcgwkMjYfNzFB3Qhfg26jf5nssaTfw0U+sAX0=";
    };
  };
  "\"graphql.vscode-graphql\"" = {
    pname = "\"graphql.vscode-graphql\"";
    version = "0.8.5";
    src = fetchurl {
      url = "https://graphql.gallery.vsassets.io/_apis/public/gallery/publisher/graphql/extension/vscode-graphql/0.8.5/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-graphql-0.8.5.zip";
      sha256 = "sha256-hmMD3+Om1SPBST1wnyHRwvJESLbpYl2aaiNZPYmYRNQ=";
    };
  };
  "\"graphql.vscode-graphql-execution\"" = {
    pname = "\"graphql.vscode-graphql-execution\"";
    version = "0.1.7";
    src = fetchurl {
      url = "https://graphql.gallery.vsassets.io/_apis/public/gallery/publisher/graphql/extension/vscode-graphql-execution/0.1.7/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-graphql-execution-0.1.7.zip";
      sha256 = "sha256-YMp/56BGAuVuMcTJtKsCi+UlznUKMK5guxZy2P682ws=";
    };
  };
  "\"graphql.vscode-graphql-syntax\"" = {
    pname = "\"graphql.vscode-graphql-syntax\"";
    version = "1.0.6";
    src = fetchurl {
      url = "https://graphql.gallery.vsassets.io/_apis/public/gallery/publisher/graphql/extension/vscode-graphql-syntax/1.0.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-graphql-syntax-1.0.6.zip";
      sha256 = "sha256-OScAXEchvHsCn3sjWcm9641yzgT+7iwO40rOAeHlmVw=";
    };
  };
  "\"hashicorp.terraform\"" = {
    pname = "\"hashicorp.terraform\"";
    version = "2.25.2";
    src = fetchurl {
      url = "https://hashicorp.gallery.vsassets.io/_apis/public/gallery/publisher/hashicorp/extension/terraform/2.25.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "terraform-2.25.2.zip";
      sha256 = "sha256-fbhm+oiIQQZoEZeOeMcjaQX30OuwM1x+2f1VNwSvkI0=";
    };
  };
  "\"ipedrazas.kubernetes-snippets\"" = {
    pname = "\"ipedrazas.kubernetes-snippets\"";
    version = "0.1.9";
    src = fetchurl {
      url = "https://ipedrazas.gallery.vsassets.io/_apis/public/gallery/publisher/ipedrazas/extension/kubernetes-snippets/0.1.9/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "kubernetes-snippets-0.1.9.zip";
      sha256 = "sha256-BlPEzRSe2NfRPjyShepa2DEhe1Jgiq7bXk2ze3eqwT0=";
    };
  };
  "\"iterative.dvc\"" = {
    pname = "\"iterative.dvc\"";
    version = "0.5.39";
    src = fetchurl {
      url = "https://iterative.gallery.vsassets.io/_apis/public/gallery/publisher/iterative/extension/dvc/0.5.39/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "dvc-0.5.39.zip";
      sha256 = "sha256-AgfdWpp6ePB6lo3I1b9KpvwMvNwyLuw2BOUHcVRYleY=";
    };
  };
  "\"ivory-lab.jenkinsfile-support\"" = {
    pname = "\"ivory-lab.jenkinsfile-support\"";
    version = "1.1.0";
    src = fetchurl {
      url = "https://ivory-lab.gallery.vsassets.io/_apis/public/gallery/publisher/ivory-lab/extension/jenkinsfile-support/1.1.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "jenkinsfile-support-1.1.0.zip";
      sha256 = "sha256-amW9jFeA4YVi8iN7pEOUCU0QA9fANtB7DlnMz9AEolQ=";
    };
  };
  "\"janjoerke.jenkins-pipeline-linter-connector\"" = {
    pname = "\"janjoerke.jenkins-pipeline-linter-connector\"";
    version = "1.2.0";
    src = fetchurl {
      url = "https://janjoerke.gallery.vsassets.io/_apis/public/gallery/publisher/janjoerke/extension/jenkins-pipeline-linter-connector/1.2.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "jenkins-pipeline-linter-connector-1.2.0.zip";
      sha256 = "sha256-L+rMNS/pNseioBqVbUrLdd/m5wpzrYfeLhoyJUcIYAM=";
    };
  };
  "\"jeff-hykin.better-cpp-syntax\"" = {
    pname = "\"jeff-hykin.better-cpp-syntax\"";
    version = "1.17.2";
    src = fetchurl {
      url = "https://jeff-hykin.gallery.vsassets.io/_apis/public/gallery/publisher/jeff-hykin/extension/better-cpp-syntax/1.17.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "better-cpp-syntax-1.17.2.zip";
      sha256 = "sha256-p3SKu9FbtuP6in2dSsr5a0aB5W+YNQ0kMgMJoDYrhcU=";
    };
  };
  "\"jnoortheen.nix-ide\"" = {
    pname = "\"jnoortheen.nix-ide\"";
    version = "0.2.1";
    src = fetchurl {
      url = "https://jnoortheen.gallery.vsassets.io/_apis/public/gallery/publisher/jnoortheen/extension/nix-ide/0.2.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "nix-ide-0.2.1.zip";
      sha256 = "sha256-yC4ybThMFA2ncGhp8BYD7IrwYiDU3226hewsRvJYKy4=";
    };
  };
  "\"josetr.cmake-language-support-vscode\"" = {
    pname = "\"josetr.cmake-language-support-vscode\"";
    version = "0.0.9";
    src = fetchurl {
      url = "https://josetr.gallery.vsassets.io/_apis/public/gallery/publisher/josetr/extension/cmake-language-support-vscode/0.0.9/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "cmake-language-support-vscode-0.0.9.zip";
      sha256 = "sha256-LNtXYZ65Lka1lpxeKozK6LB0yaxAjHsfVsCJ8ILX8io=";
    };
  };
  "\"jq-syntax-highlighting.jq-syntax-highlighting\"" = {
    pname = "\"jq-syntax-highlighting.jq-syntax-highlighting\"";
    version = "0.0.2";
    src = fetchurl {
      url = "https://jq-syntax-highlighting.gallery.vsassets.io/_apis/public/gallery/publisher/jq-syntax-highlighting/extension/jq-syntax-highlighting/0.0.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "jq-syntax-highlighting-0.0.2.zip";
      sha256 = "sha256-Bwq+aZuDmzjHw+ZnIWlL4aGz6UnqxaKm5WUko0yuIWE=";
    };
  };
  "\"kamadorueda.alejandra\"" = {
    pname = "\"kamadorueda.alejandra\"";
    version = "1.0.0";
    src = fetchurl {
      url = "https://kamadorueda.gallery.vsassets.io/_apis/public/gallery/publisher/kamadorueda/extension/alejandra/1.0.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "alejandra-1.0.0.zip";
      sha256 = "sha256-COlEjKhm8tK5XfOjrpVUDQ7x3JaOLiYoZ4MdwTL8ktk=";
    };
  };
  "\"lunuan.kubernetes-templates\"" = {
    pname = "\"lunuan.kubernetes-templates\"";
    version = "1.3.1";
    src = fetchurl {
      url = "https://lunuan.gallery.vsassets.io/_apis/public/gallery/publisher/lunuan/extension/kubernetes-templates/1.3.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "kubernetes-templates-1.3.1.zip";
      sha256 = "sha256-1XS28VLbdSQjAAnCrvid/aE8GA2WReB9Roa6E3PqXi4=";
    };
  };
  "\"maarti.jenkins-doc\"" = {
    pname = "\"maarti.jenkins-doc\"";
    version = "1.7.0";
    src = fetchurl {
      url = "https://maarti.gallery.vsassets.io/_apis/public/gallery/publisher/maarti/extension/jenkins-doc/1.7.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "jenkins-doc-1.7.0.zip";
      sha256 = "sha256-/1u83+dWFeyV+Q3P4yAO6CvigBS6rh7KN1oPCM7vzPs=";
    };
  };
  "\"mads-hartmann.bash-ide-vscode\"" = {
    pname = "\"mads-hartmann.bash-ide-vscode\"";
    version = "1.32.0";
    src = fetchurl {
      url = "https://mads-hartmann.gallery.vsassets.io/_apis/public/gallery/publisher/mads-hartmann/extension/bash-ide-vscode/1.32.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "bash-ide-vscode-1.32.0.zip";
      sha256 = "sha256-526t92LHA49QoZF+bfXvjg/dA7KycrgBJiO3KjTNKO8=";
    };
  };
  "\"ms-azuretools.vscode-docker\"" = {
    pname = "\"ms-azuretools.vscode-docker\"";
    version = "1.23.3";
    src = fetchurl {
      url = "https://ms-azuretools.gallery.vsassets.io/_apis/public/gallery/publisher/ms-azuretools/extension/vscode-docker/1.23.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-docker-1.23.3.zip";
      sha256 = "sha256-0qflugzWA1pV0PVWGTzOjdxM/0G8hTLOozoXCAdQnRY=";
    };
  };
  "\"ms-dotnettools.vscode-dotnet-runtime\"" = {
    pname = "\"ms-dotnettools.vscode-dotnet-runtime\"";
    version = "1.6.0";
    src = fetchurl {
      url = "https://ms-dotnettools.gallery.vsassets.io/_apis/public/gallery/publisher/ms-dotnettools/extension/vscode-dotnet-runtime/1.6.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-dotnet-runtime-1.6.0.zip";
      sha256 = "sha256-A3m5IvPKgmF2Dix1/bHFGcrJYriYsFgRagkZNcWf/RA=";
    };
  };
  "\"ms-kubernetes-tools.vscode-kubernetes-tools\"" = {
    pname = "\"ms-kubernetes-tools.vscode-kubernetes-tools\"";
    version = "1.3.11";
    src = fetchurl {
      url = "https://ms-kubernetes-tools.gallery.vsassets.io/_apis/public/gallery/publisher/ms-kubernetes-tools/extension/vscode-kubernetes-tools/1.3.11/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-kubernetes-tools-1.3.11.zip";
      sha256 = "sha256-I2ud9d4VtgiiIT0MeoaMThgjLYtSuftFVZHVJTMlJ8s=";
    };
  };
  "\"ms-python.isort\"" = {
    pname = "\"ms-python.isort\"";
    version = "2022.9.13271012";
    src = fetchurl {
      url = "https://ms-python.gallery.vsassets.io/_apis/public/gallery/publisher/ms-python/extension/isort/2022.9.13271012/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "isort-2022.9.13271012.zip";
      sha256 = "sha256-807ec3L6YWR9xqOhj6OCeiw/MenGgMFc6piW0+VICMc=";
    };
  };
  "\"ms-python.python\"" = {
    pname = "\"ms-python.python\"";
    version = "2023.1.10271009";
    src = fetchurl {
      url = "https://ms-python.gallery.vsassets.io/_apis/public/gallery/publisher/ms-python/extension/python/2023.1.10271009/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "python-2023.1.10271009.zip";
      sha256 = "sha256-5IEHqOI7yPffPcREGs+aLjAjvKDlzrwpCRlxwsCLC+E=";
    };
  };
  "\"ms-python.vscode-pylance\"" = {
    pname = "\"ms-python.vscode-pylance\"";
    version = "2023.1.41";
    src = fetchurl {
      url = "https://ms-python.gallery.vsassets.io/_apis/public/gallery/publisher/ms-python/extension/vscode-pylance/2023.1.41/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-pylance-2023.1.41.zip";
      sha256 = "sha256-IqgL4QNWRlAR5IQJ0hlTbLXWbYXwmTbDe5PJaiRsP7o=";
    };
  };
  "\"ms-toolsai.jupyter\"" = {
    pname = "\"ms-toolsai.jupyter\"";
    version = "2023.1.2000281008";
    src = fetchurl {
      url = "https://ms-toolsai.gallery.vsassets.io/_apis/public/gallery/publisher/ms-toolsai/extension/jupyter/2023.1.2000281008/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "jupyter-2023.1.2000281008.zip";
      sha256 = "sha256-Dee4MCLUq9caXqUi1+p5jog2rPIpMC+XO3jchRtq00s=";
    };
  };
  "\"ms-toolsai.jupyter-keymap\"" = {
    pname = "\"ms-toolsai.jupyter-keymap\"";
    version = "1.0.0";
    src = fetchurl {
      url = "https://ms-toolsai.gallery.vsassets.io/_apis/public/gallery/publisher/ms-toolsai/extension/jupyter-keymap/1.0.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "jupyter-keymap-1.0.0.zip";
      sha256 = "sha256-aP9mRvNfJ/fXSZk286FPo9gH80qwqm8mTDQ2BR+lfHI=";
    };
  };
  "\"ms-toolsai.jupyter-renderers\"" = {
    pname = "\"ms-toolsai.jupyter-renderers\"";
    version = "1.0.14";
    src = fetchurl {
      url = "https://ms-toolsai.gallery.vsassets.io/_apis/public/gallery/publisher/ms-toolsai/extension/jupyter-renderers/1.0.14/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "jupyter-renderers-1.0.14.zip";
      sha256 = "sha256-yBGAeCLvJlbRqYjq8vDi7HcuautPWTHpWqHk16++bx0=";
    };
  };
  "\"ms-toolsai.vscode-jupyter-cell-tags\"" = {
    pname = "\"ms-toolsai.vscode-jupyter-cell-tags\"";
    version = "0.1.6";
    src = fetchurl {
      url = "https://ms-toolsai.gallery.vsassets.io/_apis/public/gallery/publisher/ms-toolsai/extension/vscode-jupyter-cell-tags/0.1.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-jupyter-cell-tags-0.1.6.zip";
      sha256 = "sha256-YW7Nv3maqPCyZ/f05XbHjzbao6I8Wtr8DHQhNYH6Y+k=";
    };
  };
  "\"ms-toolsai.vscode-jupyter-slideshow\"" = {
    pname = "\"ms-toolsai.vscode-jupyter-slideshow\"";
    version = "0.1.5";
    src = fetchurl {
      url = "https://ms-toolsai.gallery.vsassets.io/_apis/public/gallery/publisher/ms-toolsai/extension/vscode-jupyter-slideshow/0.1.5/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-jupyter-slideshow-0.1.5.zip";
      sha256 = "sha256-J/pPn+MK/NQX+P+7I178S9G7Uyop4s6Hi33z/ecu2dw=";
    };
  };
  "\"ms-vscode-remote.remote-containers\"" = {
    pname = "\"ms-vscode-remote.remote-containers\"";
    version = "0.274.0";
    src = fetchurl {
      url = "https://ms-vscode-remote.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode-remote/extension/remote-containers/0.274.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "remote-containers-0.274.0.zip";
      sha256 = "sha256-sIe6kB7lJYyaM0IecROxtUnorw3usPUN4pMtpLOc+ng=";
    };
  };
  "\"ms-vscode-remote.remote-ssh\"" = {
    pname = "\"ms-vscode-remote.remote-ssh\"";
    version = "0.95.2023012415";
    src = fetchurl {
      url = "https://ms-vscode-remote.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode-remote/extension/remote-ssh/0.95.2023012415/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "remote-ssh-0.95.2023012415.zip";
      sha256 = "sha256-CS+xZnzUCfF8TGPek5YU86+FHfRoKhz7BkeDE4+vgP4=";
    };
  };
  "\"ms-vscode-remote.remote-ssh-edit\"" = {
    pname = "\"ms-vscode-remote.remote-ssh-edit\"";
    version = "0.84.0";
    src = fetchurl {
      url = "https://ms-vscode-remote.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode-remote/extension/remote-ssh-edit/0.84.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "remote-ssh-edit-0.84.0.zip";
      sha256 = "sha256-33jHWC8K0TWJG54m6FqnYEotKqNxkcd/D14TFz6dgmc=";
    };
  };
  "\"ms-vscode-remote.remote-wsl\"" = {
    pname = "\"ms-vscode-remote.remote-wsl\"";
    version = "0.75.1";
    src = fetchurl {
      url = "https://ms-vscode-remote.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode-remote/extension/remote-wsl/0.75.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "remote-wsl-0.75.1.zip";
      sha256 = "sha256-uXv+pLhwvXMjYOlks6SvUs39cuJ7gMlRsiSChE+GjU0=";
    };
  };
  "\"ms-vscode-remote.vscode-remote-extensionpack\"" = {
    pname = "\"ms-vscode-remote.vscode-remote-extensionpack\"";
    version = "0.23.0";
    src = fetchurl {
      url = "https://ms-vscode-remote.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode-remote/extension/vscode-remote-extensionpack/0.23.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-remote-extensionpack-0.23.0.zip";
      sha256 = "sha256-Ltf3Ng6F8lgDBxjg1VQlkkaxFjd5IDxyt2kTNs2Q1yI=";
    };
  };
  "\"ms-vscode.cmake-tools\"" = {
    pname = "\"ms-vscode.cmake-tools\"";
    version = "1.14.4";
    src = fetchurl {
      url = "https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/cmake-tools/1.14.4/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "cmake-tools-1.14.4.zip";
      sha256 = "sha256-O0+/vcsonBNqjvWpTI3jAC6fXsvoEa+2ucJrQuViZiM=";
    };
  };
  "\"ms-vscode.cpptools-extension-pack\"" = {
    pname = "\"ms-vscode.cpptools-extension-pack\"";
    version = "1.3.0";
    src = fetchurl {
      url = "https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/cpptools-extension-pack/1.3.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "cpptools-extension-pack-1.3.0.zip";
      sha256 = "sha256-rHST7CYCVins3fqXC+FYiS5Xgcjmi7QW7M4yFrUR04U=";
    };
  };
  "\"ms-vscode.cpptools-themes\"" = {
    pname = "\"ms-vscode.cpptools-themes\"";
    version = "2.0.0";
    src = fetchurl {
      url = "https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/cpptools-themes/2.0.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "cpptools-themes-2.0.0.zip";
      sha256 = "sha256-YWA5UsA+cgvI66uB9d9smwghmsqf3vZPFNpSCK+DJxc=";
    };
  };
  "\"ms-vscode.makefile-tools\"" = {
    pname = "\"ms-vscode.makefile-tools\"";
    version = "0.6.0";
    src = fetchurl {
      url = "https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/makefile-tools/0.6.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "makefile-tools-0.6.0.zip";
      sha256 = "sha256-Sd1bLdRBdLVK8y09wL/CJF+/kThPTH8MHw2mFQt+6h8=";
    };
  };
  "\"natqe.reload\"" = {
    pname = "\"natqe.reload\"";
    version = "0.0.6";
    src = fetchurl {
      url = "https://natqe.gallery.vsassets.io/_apis/public/gallery/publisher/natqe/extension/reload/0.0.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "reload-0.0.6.zip";
      sha256 = "sha256-bTFLk3sCJb7ztkC/Cxci6n7RbcyNjEYNKREUf9wDQRU=";
    };
  };
  "\"nelite.vscode-anime-motivator\"" = {
    pname = "\"nelite.vscode-anime-motivator\"";
    version = "1.0.0";
    src = fetchurl {
      url = "https://nelite.gallery.vsassets.io/_apis/public/gallery/publisher/nelite/extension/vscode-anime-motivator/1.0.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-anime-motivator-1.0.0.zip";
      sha256 = "sha256-bQlZzACE4cl/8FnIcCMRk+UkIb7HztW+gYpfR1T+DCk=";
    };
  };
  "\"nicolasvuillamy.vscode-groovy-lint\"" = {
    pname = "\"nicolasvuillamy.vscode-groovy-lint\"";
    version = "2.0.0";
    src = fetchurl {
      url = "https://nicolasvuillamy.gallery.vsassets.io/_apis/public/gallery/publisher/nicolasvuillamy/extension/vscode-groovy-lint/2.0.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-groovy-lint-2.0.0.zip";
      sha256 = "sha256-iHEIbxXdPQbT2gRu1fUxKOzu/GEpBFwsw4k+lLdVVIc=";
    };
  };
  "\"octref.vetur\"" = {
    pname = "\"octref.vetur\"";
    version = "0.36.1";
    src = fetchurl {
      url = "https://octref.gallery.vsassets.io/_apis/public/gallery/publisher/octref/extension/vetur/0.36.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vetur-0.36.1.zip";
      sha256 = "sha256-5UXpVWkYMQfWTofPgz0ytIBIj+IGaaR1mUwrvIQ0Fto=";
    };
  };
  "\"platformio.platformio-ide\"" = {
    pname = "\"platformio.platformio-ide\"";
    version = "2.99.4";
    src = fetchurl {
      url = "https://platformio.gallery.vsassets.io/_apis/public/gallery/publisher/platformio/extension/platformio-ide/2.99.4/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "platformio-ide-2.99.4.zip";
      sha256 = "sha256-xkvzmSW/sxalRmdIhfwkGqACWJpiZ/xD79k8cm4LhSU=";
    };
  };
  "\"plorefice.devicetree\"" = {
    pname = "\"plorefice.devicetree\"";
    version = "0.1.1";
    src = fetchurl {
      url = "https://plorefice.gallery.vsassets.io/_apis/public/gallery/publisher/plorefice/extension/devicetree/0.1.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "devicetree-0.1.1.zip";
      sha256 = "sha256-udyeY8OuI9+c26WMR63NqElyJLxdMqgOXkkmWF8233k=";
    };
  };
  "\"redhat.java\"" = {
    pname = "\"redhat.java\"";
    version = "1.15.2023012603";
    src = fetchurl {
      url = "https://redhat.gallery.vsassets.io/_apis/public/gallery/publisher/redhat/extension/java/1.15.2023012603/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "java-1.15.2023012603.zip";
      sha256 = "sha256-Fh6mLFKlfD+fBObkxcqRVRIcv+9umYnGbgcBi3VkStA=";
    };
  };
  "\"redhat.vscode-commons\"" = {
    pname = "\"redhat.vscode-commons\"";
    version = "0.0.6";
    src = fetchurl {
      url = "https://redhat.gallery.vsassets.io/_apis/public/gallery/publisher/redhat/extension/vscode-commons/0.0.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-commons-0.0.6.zip";
      sha256 = "sha256-tqjGKrQ6fhjco7/sgh2jaJCpikXyzeCOkHM8nRekFq0=";
    };
  };
  "\"redhat.vscode-xml\"" = {
    pname = "\"redhat.vscode-xml\"";
    version = "0.24.2023012703";
    src = fetchurl {
      url = "https://redhat.gallery.vsassets.io/_apis/public/gallery/publisher/redhat/extension/vscode-xml/0.24.2023012703/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-xml-0.24.2023012703.zip";
      sha256 = "sha256-hMWKeq2MzRNNb034ew4IXa0WD8/v+8frCcLBHxPp1UM=";
    };
  };
  "\"redhat.vscode-yaml\"" = {
    pname = "\"redhat.vscode-yaml\"";
    version = "1.11.10112022";
    src = fetchurl {
      url = "https://redhat.gallery.vsassets.io/_apis/public/gallery/publisher/redhat/extension/vscode-yaml/1.11.10112022/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-yaml-1.11.10112022.zip";
      sha256 = "sha256-/ZD3LOf6d5dJJW7eGZgkrf4hj1CXZJNI0u06Bnmyo0Q=";
    };
  };
  "\"roscop.activefileinstatusbar\"" = {
    pname = "\"roscop.activefileinstatusbar\"";
    version = "1.0.3";
    src = fetchurl {
      url = "https://roscop.gallery.vsassets.io/_apis/public/gallery/publisher/roscop/extension/activefileinstatusbar/1.0.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "activefileinstatusbar-1.0.3.zip";
      sha256 = "sha256-5GJODdKL8949a8KR2O7hGsRgAknfPyNEJ+9aiEYYemk=";
    };
  };
  "\"tabeyti.jenkins-jack\"" = {
    pname = "\"tabeyti.jenkins-jack\"";
    version = "1.2.1";
    src = fetchurl {
      url = "https://tabeyti.gallery.vsassets.io/_apis/public/gallery/publisher/tabeyti/extension/jenkins-jack/1.2.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "jenkins-jack-1.2.1.zip";
      sha256 = "sha256-CF2jj8qGzF3gdKT92I0sLh4TuYPHplrwgCGb1VChqgs=";
    };
  };
  "\"tim-koehler.helm-intellisense\"" = {
    pname = "\"tim-koehler.helm-intellisense\"";
    version = "0.14.3";
    src = fetchurl {
      url = "https://tim-koehler.gallery.vsassets.io/_apis/public/gallery/publisher/tim-koehler/extension/helm-intellisense/0.14.3/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "helm-intellisense-0.14.3.zip";
      sha256 = "sha256-TcXn8n6mKEFpnP8dyv+nXBjsyfUfJNgdL9iSZwA5eo0=";
    };
  };
  "\"twxs.cmake\"" = {
    pname = "\"twxs.cmake\"";
    version = "0.0.17";
    src = fetchurl {
      url = "https://twxs.gallery.vsassets.io/_apis/public/gallery/publisher/twxs/extension/cmake/0.0.17/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "cmake-0.0.17.zip";
      sha256 = "sha256-CFiva1AO/oHpszbpd7lLtDzbv1Yi55yQOQPP/kCTH4Y=";
    };
  };
  "\"visualstudioexptteam.intellicode-api-usage-examples\"" = {
    pname = "\"visualstudioexptteam.intellicode-api-usage-examples\"";
    version = "0.2.7";
    src = fetchurl {
      url = "https://visualstudioexptteam.gallery.vsassets.io/_apis/public/gallery/publisher/visualstudioexptteam/extension/intellicode-api-usage-examples/0.2.7/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "intellicode-api-usage-examples-0.2.7.zip";
      sha256 = "sha256-SJN5w9DCtGaCXCXXtUMhdwuajd9Az01oqHdBQ9KeQyc=";
    };
  };
  "\"visualstudioexptteam.vscodeintellicode\"" = {
    pname = "\"visualstudioexptteam.vscodeintellicode\"";
    version = "1.2.30";
    src = fetchurl {
      url = "https://visualstudioexptteam.gallery.vsassets.io/_apis/public/gallery/publisher/visualstudioexptteam/extension/vscodeintellicode/1.2.30/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscodeintellicode-1.2.30.zip";
      sha256 = "sha256-f2Gn+W0QHN8jD5aCG+P93Y+JDr/vs2ldGL7uQwBK4lE=";
    };
  };
  "\"vscjava.vscode-java-debug\"" = {
    pname = "\"vscjava.vscode-java-debug\"";
    version = "0.47.2023011221";
    src = fetchurl {
      url = "https://vscjava.gallery.vsassets.io/_apis/public/gallery/publisher/vscjava/extension/vscode-java-debug/0.47.2023011221/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-java-debug-0.47.2023011221.zip";
      sha256 = "sha256-Zoe6RQpPasfTLHyfNPMNnKJ5Nikcqr4jj+Gz0yw8yzY=";
    };
  };
  "\"vscjava.vscode-java-dependency\"" = {
    pname = "\"vscjava.vscode-java-dependency\"";
    version = "0.21.2023011900";
    src = fetchurl {
      url = "https://vscjava.gallery.vsassets.io/_apis/public/gallery/publisher/vscjava/extension/vscode-java-dependency/0.21.2023011900/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-java-dependency-0.21.2023011900.zip";
      sha256 = "sha256-Xqi4sb+zeKEHac+xq9hu3cRQpb0vPmamhBf6+fyyF80=";
    };
  };
  "\"vscjava.vscode-java-pack\"" = {
    pname = "\"vscjava.vscode-java-pack\"";
    version = "0.25.2022112900";
    src = fetchurl {
      url = "https://vscjava.gallery.vsassets.io/_apis/public/gallery/publisher/vscjava/extension/vscode-java-pack/0.25.2022112900/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-java-pack-0.25.2022112900.zip";
      sha256 = "sha256-DY8ZdM3d3jIfH8kHw1h14kR8k8m7xCFwW324k5XW6mU=";
    };
  };
  "\"vscjava.vscode-java-test\"" = {
    pname = "\"vscjava.vscode-java-test\"";
    version = "0.37.2022121501";
    src = fetchurl {
      url = "https://vscjava.gallery.vsassets.io/_apis/public/gallery/publisher/vscjava/extension/vscode-java-test/0.37.2022121501/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-java-test-0.37.2022121501.zip";
      sha256 = "sha256-To2oEXoiIMxqjHef20e7yChT3wX8l7g6AjtsUywGUNo=";
    };
  };
  "\"vscjava.vscode-maven\"" = {
    pname = "\"vscjava.vscode-maven\"";
    version = "0.40.2023011903";
    src = fetchurl {
      url = "https://vscjava.gallery.vsassets.io/_apis/public/gallery/publisher/vscjava/extension/vscode-maven/0.40.2023011903/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-maven-0.40.2023011903.zip";
      sha256 = "sha256-jTHSsZYGPWst/hIKQ8S+4/L0yokwOjLGiTz0W9Tq/8A=";
    };
  };
  "\"whi-tw.klipper-config-syntax\"" = {
    pname = "\"whi-tw.klipper-config-syntax\"";
    version = "0.2.1";
    src = fetchurl {
      url = "https://whi-tw.gallery.vsassets.io/_apis/public/gallery/publisher/whi-tw/extension/klipper-config-syntax/0.2.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "klipper-config-syntax-0.2.1.zip";
      sha256 = "sha256-SxhLPltowAdgfKaAqaCRxaJ2qmaGFN/8j0Hcr2v8ffg=";
    };
  };
  "\"xadillax.viml\"" = {
    pname = "\"xadillax.viml\"";
    version = "2.1.2";
    src = fetchurl {
      url = "https://xadillax.gallery.vsassets.io/_apis/public/gallery/publisher/xadillax/extension/viml/2.1.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "viml-2.1.2.zip";
      sha256 = "sha256-n91Rj1Rpp7j7gndkt0bV+jT1nRMv7+coVoSL5c7Ii3A=";
    };
  };
  "\"yzane.markdown-pdf\"" = {
    pname = "\"yzane.markdown-pdf\"";
    version = "1.4.4";
    src = fetchurl {
      url = "https://yzane.gallery.vsassets.io/_apis/public/gallery/publisher/yzane/extension/markdown-pdf/1.4.4/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "markdown-pdf-1.4.4.zip";
      sha256 = "sha256-Tt1UF1i7bgWm/jRP6IG5UOQcfe5YOeCx6Hxs/bnkkgE=";
    };
  };
}
