# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  camera-streamer = {
    pname = "camera-streamer";
    version = "v0.2.8";
    src = fetchFromGitHub {
      owner = "ayufan";
      repo = "camera-streamer";
      rev = "v0.2.8";
      fetchSubmodules = true;
      sha256 = "sha256-8vV8BMFoDeh22I1/qxk6zttJROaD/lrThBxXHZSPpT4=";
    };
  };
  katapult = {
    pname = "katapult";
    version = "ec4df2e45a7c5ceb95253c9441a0a04c1da444fd";
    src = fetchFromGitHub {
      owner = "Arksine";
      repo = "katapult";
      rev = "ec4df2e45a7c5ceb95253c9441a0a04c1da444fd";
      fetchSubmodules = false;
      sha256 = "sha256-SaZEVGGoeJyedUd+mADryILpTdAPvYuvdnNQOIoqxnY=";
    };
    date = "2023-12-15";
  };
  klipper = {
    pname = "klipper";
    version = "9f41f53c5e364694b9b41279b3b3aee34250b93a";
    src = fetchFromGitHub {
      owner = "Klipper3d";
      repo = "klipper";
      rev = "9f41f53c5e364694b9b41279b3b3aee34250b93a";
      fetchSubmodules = false;
      sha256 = "sha256-9LNNRNgRmjB25ioAt7zEoGKzuwHMD1Lq2U1w8XE9+0E=";
    };
    date = "2024-01-28";
  };
  klipper-ercf = {
    pname = "klipper-ercf";
    version = "fb9a6c7daaf881ab507368386e733a800b26f595";
    src = fetchFromGitHub {
      owner = "EtteGit";
      repo = "EnragedRabbitProject";
      rev = "fb9a6c7daaf881ab507368386e733a800b26f595";
      fetchSubmodules = false;
      sha256 = "sha256-Gwi0HiCIlTBQkHlFnmG0sZWB2xA1y5maJxF7VdfQMxU=";
    };
    date = "2022-09-02";
  };
  klipper-happy-hare = {
    pname = "klipper-happy-hare";
    version = "6b07991de744fd3d7283af7dff8d4dd1c630c83e";
    src = fetchFromGitHub {
      owner = "moggieuk";
      repo = "Happy-Hare";
      rev = "6b07991de744fd3d7283af7dff8d4dd1c630c83e";
      fetchSubmodules = false;
      sha256 = "sha256-3MsueeUcVfgrLSStQQ7pZ0IgiA0xKmaIHARyrLnXM00=";
    };
    date = "2024-01-28";
  };
  klipper-kamp = {
    pname = "klipper-kamp";
    version = "v1.1.2";
    src = fetchFromGitHub {
      owner = "kyleisah";
      repo = "Klipper-Adaptive-Meshing-Purging";
      rev = "v1.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-anBGjLtYlyrxeNVy1TEMcAGTVUFrGClLuoJZuo3xlDM=";
    };
  };
  klipper-klicky-probe = {
    pname = "klipper-klicky-probe";
    version = "f8dad75e072ed3cedd6e2179ff192917548deb00";
    src = fetchFromGitHub {
      owner = "jlas1";
      repo = "Klicky-Probe";
      rev = "f8dad75e072ed3cedd6e2179ff192917548deb00";
      fetchSubmodules = false;
      sha256 = "sha256-y0gy5aupACq7d/e+uFZk7ztiOQf4K8Mte/v0tWwRzyI=";
    };
    date = "2023-08-16";
  };
  klipper-led_effect = {
    pname = "klipper-led_effect";
    version = "c735fe52e1070632919f125513a0552e03739a5f";
    src = fetchFromGitHub {
      owner = "julianschill";
      repo = "klipper-led_effect";
      rev = "c735fe52e1070632919f125513a0552e03739a5f";
      fetchSubmodules = false;
      sha256 = "sha256-68l6iEnv+B8UewHFHA3dmiXFydKUUdCTtq0RsAgfN9Y=";
    };
    date = "2023-10-14";
  };
  klipper-screen = {
    pname = "klipper-screen";
    version = "acb187970f9a6c96118e26533a4bb279591a6700";
    src = fetchFromGitHub {
      owner = "jordanruthe";
      repo = "KlipperScreen";
      rev = "acb187970f9a6c96118e26533a4bb279591a6700";
      fetchSubmodules = false;
      sha256 = "sha256-Rfx80RWTnEne5DEYTP1FQGreQ7SlSnPHZkVlDpRqjqM=";
    };
    date = "2024-01-27";
  };
  klipper-z-calibration = {
    pname = "klipper-z-calibration";
    version = "v1.0.2";
    src = fetchFromGitHub {
      owner = "protoloft";
      repo = "klipper_z_calibration";
      rev = "v1.0.2";
      fetchSubmodules = false;
      sha256 = "sha256-QDsr09aIP09pI2r18atTRvbbMBS0rbjeiWOSnp9nRUk=";
    };
  };
  libdatachannel0_17 = {
    pname = "libdatachannel0_17";
    version = "v0.17.10";
    src = fetchFromGitHub {
      owner = "paullouisageneau";
      repo = "libdatachannel";
      rev = "v0.17.10";
      fetchSubmodules = false;
      sha256 = "sha256-3f84GxAgQiObe+DYuTQABvK+RTihKKFKaf48lscUex4=";
    };
  };
  libjuice = {
    pname = "libjuice";
    version = "v1.0.4";
    src = fetchFromGitHub {
      owner = "paullouisageneau";
      repo = "libjuice";
      rev = "v1.0.4";
      fetchSubmodules = false;
      sha256 = "sha256-LAqi5F6okhGj0LyJasPKRkUz6InlM6rbYN+1sX1N4Qo=";
    };
  };
  live555 = {
    pname = "live555";
    version = "2020.03.06";
    src = fetchTarball {
      url = "https://download.videolan.org/pub/contrib/live555/live.2020.03.06.tar.gz";
      sha256 = "sha256-UxunbrJC6UVlwexso/cuH9m+mUSf7WEPMLincUrqDWE=";
    };
  };
  mainsail = {
    pname = "mainsail";
    version = "65a62cb89024b653347612d747a9fcfb4d62a4e3";
    src = fetchFromGitHub {
      owner = "mainsail-crew";
      repo = "mainsail";
      rev = "65a62cb89024b653347612d747a9fcfb4d62a4e3";
      fetchSubmodules = false;
      sha256 = "sha256-P8EPblLfnDI6wn8fwSPJG3uFcS8aljiGSdGXcIxLckU=";
    };
    date = "2024-01-26";
  };
  mobileraker-companion = {
    pname = "mobileraker-companion";
    version = "7297fbcaa7ed724eb431605f3a5f28879f010b38";
    src = fetchFromGitHub {
      owner = "Clon1998";
      repo = "mobileraker_companion";
      rev = "7297fbcaa7ed724eb431605f3a5f28879f010b38";
      fetchSubmodules = false;
      sha256 = "sha256-iPeCaKo/XVU/8YWeNwqyEmdQuPQao8SH7LBhB55uPtA=";
    };
    date = "2024-01-02";
  };
  moonraker = {
    pname = "moonraker";
    version = "61ea86033ab8a788a5f8d1d953667bad2bdb6d13";
    src = fetchFromGitHub {
      owner = "Arksine";
      repo = "moonraker";
      rev = "61ea86033ab8a788a5f8d1d953667bad2bdb6d13";
      fetchSubmodules = false;
      sha256 = "sha256-8O+MQTE1GpmKlAr8ZH6Lm9dW1+OTLte7iBrIPS9VOx4=";
    };
    date = "2024-01-28";
  };
  python-networkmanager = {
    pname = "python-networkmanager";
    version = "2.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/p/python-networkmanager/python-networkmanager-2.2.tar.gz";
      sha256 = "sha256-3m65IdlKunVJ9CjtKzqkgqXVQ+y2lly6oPu1VasxudU=";
    };
  };
}
