# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  klipper = {
    pname = "klipper";
    version = "b9247810b90938339e87056a5d0f8a7f207d4ea4";
    src = fetchFromGitHub {
      owner = "Klipper3d";
      repo = "klipper";
      rev = "b9247810b90938339e87056a5d0f8a7f207d4ea4";
      fetchSubmodules = false;
      sha256 = "sha256-FJoSQSmlrceG9NVoEx1PvcS3IX/8Eu+Q2tzgx8DJjjc=";
    };
    date = "2023-06-23";
  };
  klipper-led_effect = {
    pname = "klipper-led_effect";
    version = "35cf587fe958fe15a07c11b60564856582890460";
    src = fetchFromGitHub {
      owner = "julianschill";
      repo = "klipper-led_effect";
      rev = "35cf587fe958fe15a07c11b60564856582890460";
      fetchSubmodules = false;
      sha256 = "sha256-AZase17sO85Bp14DocUn+m6jT8P5ABXBJFdH7t4ANog=";
    };
    date = "2023-02-04";
  };
  klipper-screen = {
    pname = "klipper-screen";
    version = "5a0df3a6280a856040941e48210a32d699b309bb";
    src = fetchFromGitHub {
      owner = "jordanruthe";
      repo = "KlipperScreen";
      rev = "5a0df3a6280a856040941e48210a32d699b309bb";
      fetchSubmodules = false;
      sha256 = "sha256-akL9Cu9y3bSPXcDwS1j6c1ruNIv+zO9cBvPRTgMchr0=";
    };
    date = "2023-06-22";
  };
  mainsail = {
    pname = "mainsail";
    version = "705065d65e8f36bf5fdc8a6bb30057a1890049e4";
    src = fetchFromGitHub {
      owner = "mainsail-crew";
      repo = "mainsail";
      rev = "705065d65e8f36bf5fdc8a6bb30057a1890049e4";
      fetchSubmodules = false;
      sha256 = "sha256-rKmvbjSqmR7ZNpI2ev6zudoKLRyBtjr/ixLL83AavaU=";
    };
    date = "2023-06-19";
  };
  moonraker = {
    pname = "moonraker";
    version = "0f4276d9b02f5e40ef3d66d689c56ef3ff381ff2";
    src = fetchFromGitHub {
      owner = "Arksine";
      repo = "moonraker";
      rev = "0f4276d9b02f5e40ef3d66d689c56ef3ff381ff2";
      fetchSubmodules = false;
      sha256 = "sha256-cT37j/7RxSgJgBwOJw4FBRMCpVxDot1qw2na3PekZ2c=";
    };
    date = "2023-06-20";
  };
  moonraker-telegram-bot = {
    pname = "moonraker-telegram-bot";
    version = "ca30751a6924ffe28e26d8d708033607ad7f8e92";
    src = fetchFromGitHub {
      owner = "nlef";
      repo = "moonraker-telegram-bot";
      rev = "ca30751a6924ffe28e26d8d708033607ad7f8e92";
      fetchSubmodules = false;
      sha256 = "sha256-a4PyQaxicSHEPwM4wgh3Z57gh1zrsHXeIUwf7lWFDXY=";
    };
    date = "2023-06-15";
  };
  python-networkmanager = {
    pname = "python-networkmanager";
    version = "2.2";
    src = fetchurl {
      url = "https://pypi.org/packages/source/p/python-networkmanager/python-networkmanager-2.2.tar.gz";
      sha256 = "sha256-3m65IdlKunVJ9CjtKzqkgqXVQ+y2lly6oPu1VasxudU=";
    };
  };
  rel = {
    pname = "rel";
    version = "ed891f2963dfe8e15133365e4c362756a0a5f282";
    src = fetchFromGitHub {
      owner = "bubbleboy14";
      repo = "registeredeventlistener";
      rev = "ed891f2963dfe8e15133365e4c362756a0a5f282";
      fetchSubmodules = false;
      sha256 = "sha256-PrhVG1NbgpYwgzFFMNI2azQjoGKOkEJdf4MrbG0tTpg=";
    };
    date = "2023-05-23";
  };
  wsaccel = {
    pname = "wsaccel";
    version = "0.6.4";
    src = fetchurl {
      url = "https://pypi.org/packages/source/w/wsaccel/wsaccel-0.6.4.tar.gz";
      sha256 = "sha256-y/ZqiLyvbGrRbVDqKSFYkVJrbpk8S8ftRLBE7m/jrT0=";
    };
  };
}
