# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  libcamera = {
    pname = "libcamera";
    version = "29156679717bec7cc4784aeba3548807f2c27fca";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera";
      rev = "29156679717bec7cc4784aeba3548807f2c27fca";
      fetchSubmodules = false;
      sha256 = "sha256-89uo3ajxozSpM4AGVIVb5GJ70giAQeyw0duIj5PRBgo=";
    };
    date = "2025-02-13";
  };
  libcamera-apps = {
    pname = "libcamera-apps";
    version = "74abee8f2de519fed9cb88d39473d1dd4cf50b62";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera-apps";
      rev = "74abee8f2de519fed9cb88d39473d1dd4cf50b62";
      fetchSubmodules = false;
      sha256 = "sha256-05E3n/+Jg/EFJZgJjkcxXmVvEBRkuprQ7Ann0EGkiMc=";
    };
    date = "2025-02-28";
  };
  mediamtx = {
    pname = "mediamtx";
    version = "6532a82670e208fc8c2bc422e0d43d5edc578dce";
    src = fetchFromGitHub {
      owner = "bluenviron";
      repo = "mediamtx";
      rev = "6532a82670e208fc8c2bc422e0d43d5edc578dce";
      fetchSubmodules = false;
      sha256 = "sha256-t4VXGcM7+M2Q5qAjON5xJxMnAIgo05Dmb6hAOzu5rMM=";
    };
    date = "2025-03-16";
  };
}
