# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  libcamera = {
    pname = "libcamera";
    version = "1230f78d2f6d38d812568fd27f7b985b9ff19e39";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera";
      rev = "1230f78d2f6d38d812568fd27f7b985b9ff19e39";
      fetchSubmodules = false;
      sha256 = "sha256-pG8QdMY9UWH+UodXi1j/hVuVFRe58vvOsf7tOrrb774=";
    };
    date = "2024-11-19";
  };
  libcamera-apps = {
    pname = "libcamera-apps";
    version = "b78871ec21b466d8cbf04430af88b660aff5a487";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera-apps";
      rev = "b78871ec21b466d8cbf04430af88b660aff5a487";
      fetchSubmodules = false;
      sha256 = "sha256-pbSCE+xe5isdsJ0RVsUZAmrhK7IBBxhKC4QzJFCkeqY=";
    };
    date = "2024-12-05";
  };
  mediamtx = {
    pname = "mediamtx";
    version = "e7b367245f40d38fbfd813abb1c8d9f8eb435c3d";
    src = fetchFromGitHub {
      owner = "bluenviron";
      repo = "mediamtx";
      rev = "e7b367245f40d38fbfd813abb1c8d9f8eb435c3d";
      fetchSubmodules = false;
      sha256 = "sha256-x982SDRuoZz87ag/HLAQAK+AEE9RvrLXO1YeWlRtxlc=";
    };
    date = "2024-12-05";
  };
}
