# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  libcamera = {
    pname = "libcamera";
    version = "bde9b04ff2ce49d343e36c86d6ae99ff53cbf11a";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera";
      rev = "bde9b04ff2ce49d343e36c86d6ae99ff53cbf11a";
      fetchSubmodules = false;
      sha256 = "sha256-tbA+FLBvIZ7wasRaqYus8vTAwJFIspUsgHlGIS8/0yU=";
    };
    date = "2023-07-20";
  };
  libcamera-apps = {
    pname = "libcamera-apps";
    version = "9e172655e257972e5da45d59a720192516f7d769";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera-apps";
      rev = "9e172655e257972e5da45d59a720192516f7d769";
      fetchSubmodules = false;
      sha256 = "sha256-1nlX6tXUbtI1rprOi7X/mStevHCw98CnriaBfHybZr8=";
    };
    date = "2023-07-21";
  };
  mediamtx = {
    pname = "mediamtx";
    version = "fcba131c988b5b16b922f0fb4e0c0b43ed5e02cf";
    src = fetchFromGitHub {
      owner = "bluenviron";
      repo = "mediamtx";
      rev = "fcba131c988b5b16b922f0fb4e0c0b43ed5e02cf";
      fetchSubmodules = false;
      sha256 = "sha256-EDYQ82Sq1SJeVJl3ZAZa/BEpHtk2zacQ51hZNlWvRbs=";
    };
    date = "2023-07-21";
  };
}
