# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  libcamera = {
    pname = "libcamera";
    version = "6ddd79b5bdbedc1f61007aed35391f1559f9e29a";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera";
      rev = "6ddd79b5bdbedc1f61007aed35391f1559f9e29a";
      fetchSubmodules = false;
      sha256 = "sha256-qqEMJzMotybf1nJp1dsz3zc910Qj0TmqCm1CwuSb1VY=";
    };
    date = "2024-06-17";
  };
  libcamera-apps = {
    pname = "libcamera-apps";
    version = "4ec534bc10b0d493f4d358bce3cde46853362148";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera-apps";
      rev = "4ec534bc10b0d493f4d358bce3cde46853362148";
      fetchSubmodules = false;
      sha256 = "sha256-I+WEv9st8VmWNOivd8/2LIfxoB2pPeV5exZJJEhy3xU=";
    };
    date = "2024-06-26";
  };
  mediamtx = {
    pname = "mediamtx";
    version = "a1dc9f45f5e2a03084274bea139ecaa2e805d659";
    src = fetchFromGitHub {
      owner = "bluenviron";
      repo = "mediamtx";
      rev = "a1dc9f45f5e2a03084274bea139ecaa2e805d659";
      fetchSubmodules = false;
      sha256 = "sha256-DlHjf1849YNeCxBBjfBLxBSvivOTXYdToFFHr3a5/L4=";
    };
    date = "2024-06-19";
  };
}
