# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
}: {
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub {
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    };
  };
  s5cmd = {
    pname = "s5cmd";
    version = "914e701426e31a5819a422a4880bdbe03304f9df";
    src = fetchFromGitHub {
      owner = "peak";
      repo = "s5cmd";
      rev = "914e701426e31a5819a422a4880bdbe03304f9df";
      fetchSubmodules = false;
      sha256 = "sha256-9sCOrwU+vyJ5JkZobi5Ypsch7Num59FpVr6bkmhMheM=";
    };
  };
  tfenv = {
    pname = "tfenv";
    version = "c05c364a0565b0bee63d97b763def4521d620884";
    src = fetchFromGitHub {
      owner = "tfutils";
      repo = "tfenv";
      rev = "c05c364a0565b0bee63d97b763def4521d620884";
      fetchSubmodules = false;
      sha256 = "sha256-2Fpaj/UQDE7PNFX9GNr4tygvKmm/X0yWVVerJ+Y6eks=";
    };
  };
  transmissionic = {
    pname = "transmissionic";
    version = "9353f9824ed279fcc8637939241609fc081a46ff";
    src = fetchFromGitHub {
      owner = "6c65726f79";
      repo = "Transmissionic";
      rev = "9353f9824ed279fcc8637939241609fc081a46ff";
      fetchSubmodules = false;
      sha256 = "sha256-aZojSGle8jWEz0SZ+GC4cfvKpfVqRuqlAzPDpb2/77M=";
    };
  };
}
