# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
}: {
  eeprom-editor = {
    pname = "eeprom-editor";
    version = "3.2.0";
    src = fetchFromGitHub {
      owner = "cp2004";
      repo = "OctoPrint-EEPROM-Marlin";
      rev = "3.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-GNeDo6PIVQ+yHglHne/WJtfgYh8KF09GY9gzfr1Le5Q=";
    };
  };
  klipper = {
    pname = "klipper";
    version = "51da02b7f8b4a691154b9c5c8f982d35beac9883";
    src = fetchFromGitHub {
      owner = "Klipper3d";
      repo = "klipper";
      rev = "51da02b7f8b4a691154b9c5c8f982d35beac9883";
      fetchSubmodules = false;
      sha256 = "sha256-n8da29LN5/fsUOD1KpbQUItwpAEPEN+IJzDolgrXB5s=";
    };
  };
  klipper-screen = {
    pname = "klipper-screen";
    version = "35571fce8acd70badf8deea9445060b2da4d4f4d";
    src = fetchFromGitHub {
      owner = "jordanruthe";
      repo = "KlipperScreen";
      rev = "35571fce8acd70badf8deea9445060b2da4d4f4d";
      fetchSubmodules = false;
      sha256 = "sha256-QyQDOMpFDywRMUmGzHui8RZNrsMbVbOY0NTxqIrQ0I0=";
    };
  };
  libcamera = {
    pname = "libcamera";
    version = "e68e0f1ed2880ea26b5e317f94e2bbd5332e1598";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera";
      rev = "e68e0f1ed2880ea26b5e317f94e2bbd5332e1598";
      fetchSubmodules = false;
      sha256 = "sha256-maeLpR3zNuSROlaGAYZMJ/Bp1GodWIchXNkjLgRrY6Y=";
    };
  };
  libcamera-apps = {
    pname = "libcamera-apps";
    version = "6bade0b112aca37fd9762d180203e376867ff09c";
    src = fetchFromGitHub {
      owner = "raspberrypi";
      repo = "libcamera-apps";
      rev = "6bade0b112aca37fd9762d180203e376867ff09c";
      fetchSubmodules = false;
      sha256 = "sha256-K57+9YTZNLHi0ljabDm1r/h5nkAIvS7Gvj25e+rcpcs=";
    };
  };
  mainsail = {
    pname = "mainsail";
    version = "6a40e6047d980d59bb1497057b0ab0acf8bc1527";
    src = fetchFromGitHub {
      owner = "mainsail-crew";
      repo = "mainsail";
      rev = "6a40e6047d980d59bb1497057b0ab0acf8bc1527";
      fetchSubmodules = false;
      sha256 = "sha256-wcJRKaRwqnRJ6Hw0zeGHtFZN8EIK3peH670Xu8LQ6YM=";
    };
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub {
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    };
  };
  moonraker = {
    pname = "moonraker";
    version = "df24e3ea7764e23148fb2f90033dc6d626071a11";
    src = fetchFromGitHub {
      owner = "Arksine";
      repo = "moonraker";
      rev = "df24e3ea7764e23148fb2f90033dc6d626071a11";
      fetchSubmodules = false;
      sha256 = "sha256-RzJQUyWSH6P3kkkgnYehHx+QLzxUn8dNQpyJCXGqwI4=";
    };
  };
  octoprint-display-layer-progress = {
    pname = "octoprint-display-layer-progress";
    version = "1.28.0";
    src = fetchFromGitHub {
      owner = "OllisGit";
      repo = "OctoPrint-DisplayLayerProgress";
      rev = "1.28.0";
      fetchSubmodules = false;
      sha256 = "sha256-FoQGv7a3ktodyQKOwR69/9Up+wPoW5NDq+k5LfP9WYs=";
    };
  };
  rtsp-simple-server = {
    pname = "rtsp-simple-server";
    version = "85ce12199aa324a8399407aac41f8b2fbaad279d";
    src = fetchFromGitHub {
      owner = "aler9";
      repo = "rtsp-simple-server";
      rev = "85ce12199aa324a8399407aac41f8b2fbaad279d";
      fetchSubmodules = false;
      sha256 = "sha256-egmTcEhfBxUw8fOpcft0Sna7zXxAfI264yZECDpWYQE=";
    };
  };
  s5cmd = {
    pname = "s5cmd";
    version = "83ce8bc6a1016bcea46da48e9090f8e761478149";
    src = fetchFromGitHub {
      owner = "peak";
      repo = "s5cmd";
      rev = "83ce8bc6a1016bcea46da48e9090f8e761478149";
      fetchSubmodules = false;
      sha256 = "sha256-8WoIUTRd2Ooot70hsAYVz9bEKKkK9Hs279RL+8D2Qfk=";
    };
  };
  tfenv = {
    pname = "tfenv";
    version = "c05c364a0565b0bee63d97b763def4521d620884";
    src = fetchFromGitHub {
      owner = "tfutils";
      repo = "tfenv";
      rev = "c05c364a0565b0bee63d97b763def4521d620884";
      fetchSubmodules = false;
      sha256 = "sha256-2Fpaj/UQDE7PNFX9GNr4tygvKmm/X0yWVVerJ+Y6eks=";
    };
  };
}
