# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  btt-linux-rockchip = {
    pname = "btt-linux-rockchip";
    version = "bpi-rk-6.1-rkr5";
    src = fetchFromGitHub {
      owner = "bigtreetech";
      repo = "linux-rockchip";
      rev = "bpi-rk-6.1-rkr5";
      fetchSubmodules = false;
      sha256 = "sha256-UeXdzByVGW8t7I/unMSHRUBMIRFNoCY1voY4UTpLqy4=";
    };
  };
  btt-u-boot = {
    pname = "btt-u-boot";
    version = "bpi-v2025.04-rc3";
    src = fetchFromGitHub {
      owner = "bigtreetech";
      repo = "u-boot";
      rev = "bpi-v2025.04-rc3";
      fetchSubmodules = false;
      sha256 = "sha256-Dtcc61orqV6HtqrYCeAO5iQfVU9KK3Jgnf+LoS8zTh0=";
    };
  };
  uboot = {
    pname = "uboot";
    version = "v2025.04-rc2";
    src = fetchFromGitHub {
      owner = "u-boot";
      repo = "u-boot";
      rev = "v2025.04-rc2";
      fetchSubmodules = false;
      sha256 = "sha256-emuw0j2m7qsamaQveM3rsWUSfi9rym9E3qYbUa3LirY=";
    };
  };
  uboot-2024-10 = {
    pname = "uboot-2024-10";
    version = "v2024.10";
    src = fetchFromGitHub {
      owner = "u-boot";
      repo = "u-boot";
      rev = "v2024.10";
      fetchSubmodules = false;
      sha256 = "sha256-UPy7XM1NGjbEt+pQr4oQrzD7wWWEtYDOPWTD+CNYMHs=";
    };
  };
}
