# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  uboot = {
    pname = "uboot";
    version = "v2025.04-rc2";
    src = fetchFromGitHub {
      owner = "u-boot";
      repo = "u-boot";
      rev = "v2025.04-rc2";
      fetchSubmodules = false;
      sha256 = "sha256-emuw0j2m7qsamaQveM3rsWUSfi9rym9E3qYbUa3LirY=";
    };
  };
}
