name: Build x86
on:
  push:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Update flake.lock"
    types: [completed]

env:
  REF: ${{ github.event_name == 'workflow_run' && 'auto/upgrade-dependencies' || github.ref }}

jobs:
  build_system:
    if: (contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name) || github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        host:
          - nixos-nas
          - nixos-depsos
          - nixos-hyperos
          - wsl-tl-wsl
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.REF }}
      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-23.05
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: truelecter
          extraPullNames: cuda-maintainers, mic92, nix-community, nrdxp
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build system configuration
        run: |
          nix build ".#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel"

  build_shell:
    runs-on: ubuntu-latest
    if: (contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name) || github.event.workflow_run.conclusion == 'success')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.REF }}
      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-23.05
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: truelecter
          extraPullNames: cuda-maintainers, mic92, nix-community, nrdxp
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build shell
        run: |
          nix develop --command "menu"
