name: Build x86 host
on:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true
      CACHIX_AUTH_TOKEN:
        required: true
jobs:
  build_system:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-23.05
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: truelecter
          extraPullNames: cuda-maintainers, mic92, nix-community, nrdxp
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build system configuration
        run: |
          nix build ".#nixosConfigurations.${{ inputs.configuration }}.config.system.build.toplevel"
