name: Build tl-mm4
on:
  push:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/build-darwin-host.yaml
    with:
      configuration: tl-mm4
    secrets: inherit
