name: Build rockiosk
on:
  push:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/build-x86-host.yaml
    with:
      configuration: rockiosk
    secrets: inherit
