name: Build darwin host
on:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true
jobs:
  build_system:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-23.11
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: truelecter
          extraPullNames: cuda-maintainers, mic92, nix-community, nrdxp
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Create builder
        env:
          BUILDER_PK: ${{secrets.AARCH64_BUILDER_PK}}
          BUILDER_HOST: ${{secrets.AARCH64_BUILDER_HOSTNAME}}
        run: |
          echo "$BUILDER_PK" | sudo tee /etc/nix/builder_ed25519 > /dev/null
          sudo chmod 600 /etc/nix/builder_ed25519

          sudo mkdir -p /var/root/.ssh
          ssh-keyscan -H "$BUILDER_HOST,linux-builder" | sudo tee -a /var/root/.ssh/known_hosts > /dev/null

          mkdir -p /etc/ssh/
          echo "Host linux-builder"                      | sudo tee -a /etc/ssh/ssh_config
          echo "  Hostname $BUILDER_HOST"                | sudo tee -a /etc/ssh/ssh_config > /dev/null
          echo "  Port 22"                               | sudo tee -a /etc/ssh/ssh_config
          echo "  HostKeyAlias linux-builder"            | sudo tee -a /etc/ssh/ssh_config
          echo "  IdentityFile /etc/nix/builder_ed25519" | sudo tee -a /etc/ssh/ssh_config
          echo "  User gha-builder"                      | sudo tee -a /etc/ssh/ssh_config

          nix store info nix-command --store ssh://linux-builder

      - name: Build system configuration
        run: |
          nix -vv build \
            --builders 'ssh-ng://linux-builder aarch64-linux /etc/nix/builder_ed25519 8' \
            ".#darwinConfigurations.${{ inputs.configuration }}.config.system.build.toplevel"
