name: Build squadbook
on:
  push:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/build-darwin-host.yaml
    with:
      configuration: squadbook
    secrets: inherit
