name: Build oracle
on:
  push:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/build-aarch64-host.yaml
    with:
      configuration: oracle
    secrets: inherit
