name: Build tl-wsl
on:
  push:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/build-x86-host.yaml
    with:
      configuration: wsl-tl-wsl
    secrets: inherit
