name: Build hyperos
on:
  push:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ./.github/base-workflows/build-x86-host.yaml
    with:
      configuration: nixos-hyperos
    secrets: inherit
