name: Build darwin host
on:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true
jobs:
  build_system:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-23.11
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: truelecter
          extraPullNames: cuda-maintainers, mic92, nix-community, nrdxp
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Start emulator
        run: |
          nix build github:nixos/nixpkgs/nixpkgs-23.11-darwin#darwin.linux-builder

          mkdir -p /etc/ssh/ssh_config.d/
          echo "Host linux-builder"                      | sudo tee -a /etc/ssh/ssh_config.d/100-linux-builder.conf
          echo "  Hostname localhost"                    | sudo tee -a /etc/ssh/ssh_config.d/100-linux-builder.conf
          echo "  Port 31022"                            | sudo tee -a /etc/ssh/ssh_config.d/100-linux-builder.conf
          echo "  HostKeyAlias linux-builder"            | sudo tee -a /etc/ssh/ssh_config.d/100-linux-builder.conf
          echo "  IdentityFile /etc/nix/builder_ed25519" | sudo tee -a /etc/ssh/ssh_config.d/100-linux-builder.conf
          echo "  User builder"                          | sudo tee -a /etc/ssh/ssh_config.d/100-linux-builder.conf

      - name: Build system configuration
        run: |
          nix run github:nixos/nixpkgs/nixpkgs-23.11-darwin#darwin.linux-builder &
          until sudo ssh linux-builder; do echo not yet online; sleep 1; done

          nix build ".#darwinConfigurations.${{ inputs.configuration }}.config.system.build.toplevel"
